- repo2docker/app.py
- repo2docker/detectors.py
- repo2docker/utils.py
- only capture subprocess output when doing json logging
- opt-in to json logging with `--json-logs`
- don't strip line endings in captured log messages (needed for distinguishing between CR and LF)
- yield lines that end with CR (needed for live-updating CR-style progress bars)
> line endings!

- repo2docker/app.py
- repo2docker/detectors.py
only run on dockerfiles with `FROM andrewosh/binder-base`
- installs required versions of ipykernel, jupyterhub, notebook
- registers kernelspecs explicitly
- launches notebook server with python3 env
- removes nb_conda_kernels, which was causing trouble when not launched from the root env
- sets JUPYTER_PATH so kernelspecs and extensions that were being installed into the python 2 env should still be picked up
> add LegacyBinderDockerfile buildpack

- repo2docker/detectors.py
install in its own prefix as well
Python 2 notebooks were running with Python 3 due to a bad kernelspec
> tweak how the python2 kerenl is installed

- docs/source/conf.py
- docs/source/index.rst
- tests/conda/requirements/README.rst
- tests/conda/simple/README.rst
- tests/julia/pyplot/README.rst
This is a quick first-stab at auto-generating some documentation from our tests. It requires that there is a `README.rst` file inside any of the folders that we want to document. If it finds this file, then it adds a section that includes whatever is inside `README.rst` for that folder, and then shows the contents of the other files in that folder.
I added the readme file for a few sample repos so we can see how it looks. For some reason github isn't serving my website now so it's hard for me to show you, but here's a screenshot of what it looks like:
> adding doc generation from the tests

- repo2docker/detectors.py
Too many things require npm to build now.
> Add npm to base image

- repo2docker/app.py
- setup.py
If --debug is passed, it'll print the Dockerfile generated. 
Note that  the Dockefile thus produced is *not* in any way usefu outside of debuggingl -
we do a bunch of path munging and adding scripts in here (such as install-miniconda).
If it isn't useful as is now, I don't think we should encourage people to use this to print 
Dockerfiles for basing their Dockerfiles on from here, and should just write that as docs
instead.
Either way, this is still very useful for Debugging.
> Add --debug & --no-build options

- repo2docker/app.py
- repo2docker/detectors.py
- repo2docker/files/conda/environment.yml
- repo2docker/files/conda/install-miniconda.bash
- tests/dockerfile/jupyter-stack/Dockerfile
- tests/dockerfile/jupyter-stack/verify
- tests/dockerfile/legacy/verify
- tests/dockerfile/simple/Dockerfile
and respect it in all buildpacks
We probably want to eventually do the same for every other package with a hardcoded version (notebook, ipython, etc.).
In testing, I also noticed that Legacy Dockerfile isn't working at all right now because the dockerfile_appendix is ignored.
The new tests here revealed this and ought to now be fixed.
> make JUPYTERHUB_VERSION a build arg

- repo2docker/app.py
rmtree throws exceptions on a git repo checked out on a Windows filesystem. I believe that ignoring errors is ok here as app.py fully controls the checkout dir.
> More forgiving rmtree

- repo2docker/files/conda/environment.yml
How would we run commands to install JupyterLab packages which require running bash commands such as `jupyter labextension install foo`? @blink1073
> Update JupyterLab to 0.27

- repo2docker/detectors.py
- tests/conda/requirements/README.rst
- tests/conda/requirements/environment.yml
- tests/conda/requirements/verify
- tests/conda/simple/README.rst
- tests/conda/simple/verify
The most likely cause of both being present is equivalent dependencies for pip and conda users, not a single multi-stage conda environment.
If deps should be installed in conda with pip, they should be in `environment.yml` under `pip`.
> don't install requirements.txt if environment.yml is present

- .gitignore
- repo2docker/detectors.py
- tests/conda/binder-dir/.binder/environment.yml
- tests/conda/binder-dir/Dockerfile
- tests/conda/binder-dir/README.rst
- tests/conda/binder-dir/environment.yml
- tests/conda/binder-dir/verify
- tests/dockerfile/binder-dir/.binder/Dockerfile
- tests/dockerfile/binder-dir/Dockerfile
- tests/dockerfile/binder-dir/README.rst
- tests/dockerfile/binder-dir/sayhi.sh
- tests/dockerfile/binder-dir/verify
- tests/venv/binder-dir/.binder/postBuild
- tests/venv/binder-dir/.binder/requirements.txt
- tests/venv/binder-dir/README.rst
- tests/venv/binder-dir/environment.yml
- tests/venv/binder-dir/verify
If .binder exists, top-level files are ignored. This allows for top-level Dockerfiles for other uses, but binder-specific environment.yml, etc.
closes #72, #73
> Look in .binder directory for files

- Dockerfile
- travis/travis-script.bash
This cuts image size from under 300MB to under 100MB. Plus
we will never actually need this to have additional libraries
installed, since it's talking to the docker socket directly
to build new images. So switching to alpine here is worth it.
> Switch base image to alpine + fix typo causing CI to fail

- repo2docker/detectors.py
If the permissions are wrong the build will fail, which is more informative than silently ignoring the file.
cf https://github.com/jupyterhub/binderhub/issues/155 which this would have caught more promptly.
> raise on non-executable postBuild

- Dockerfile
Without this, repo2docker just fails.
Caused https://github.com/jupyterhub/mybinder.org-deploy/pull/52 to fail.
> Add git to the repo2docker docker image

- repo2docker/detectors.py
If the `binder` folder is in a package directory, then the existing setup will call `using` on the package requirements instead of `binder/REQUIRE`.  This can run into some issues if the package requires a specific version of Julia:
```
ERROR: ArgumentError: Module julia not found in current path.
Run `Pkg.add("julia")` to install the julia package.
```
> Only parse `REQUIRE` file in `binder` (if exists)

- repo2docker/app.py
This reorganizes a couple of the docstring parameters so that they more naturally follow linear time. LMK if you think there is a more intuitive ordering here. I saw that @ctb was running `--no-run` assuming it was `--no-build`, so hopefully this will catch some of those usage patterns.
This assumes the order of operations is:
build -> cmd -> run -> push
> reorganizing arguments

- repo2docker/detectors.py
Fixes  https://github.com/jupyterhub/binderhub/issues/200
> Remove intermediate containers in failed builds

- setup.py
jupyter-repo2docker is a mouthful
> Add 'repo2docker' as a script alias

- repo2docker/app.py
- repo2docker/detectors.py
- repo2docker/files/conda/install-miniconda.bash
- tests/dockerfile/binder-dir/binder/Dockerfile
- tests/dockerfile/jupyter-stack/Dockerfile
- tests/dockerfile/simple/Dockerfile
Closes #92 
Remove jupyterhub from dockerfiles, build args, and tests.
Left jupyterhub code in legacy dockerfiles and tests.
> Remove jupyterhub from default installs

- repo2docker/app.py
- repo2docker/detectors.py
- tests/dockerfile/legacy/verify
- tests/external/datasci-shallow-clone.repos.yaml
- tests/external/shallow-clone.repos.yaml
Only checkout last 50 commits from a remote repository. This helps speed
up the cloning for large repositories.
50 is the same depth to which travis clones by default. This does have the potential to fail though because there is no reason for the ref we might want to checkout to be in the last 50 commits.
WDYT?
> [MRG] Add limit on git clone depth

- repo2docker/app.py
- tests/conftest.py
- tests/external/shallow-clone.repos.yaml
Fixes the bug noticed (and reverted) here: jupyterhub/mybinder.org-deploy#112
We do not need to checkout a specific ref if none is provided. Added a test to check the behaviour.
The big question is: when does binderhub call `repo2docker` without a ref as commandline argument?
> Add handling for no ref being provided

- repo2docker/app.py
- tests/conftest.py
- tests/external/shallow-clone.repos.yaml
Reverts jupyter/repo2docker#128
It looks like shallow clones are a lot more hairy than we realized.
We discovered the following:
1. We currently have no way to figure out if a clone is shallow or not.
An option has been added to rev-parse (why rev-parse?!) but that's 
too new and not in any packaged git.
2. If your repo has under 50 commits, it will not be shallow!
3. If you try to run git fetch --unshallow on a non-shallow repo it is a fatal error
> Revert "Add handling for no ref being provided"

- repo2docker/detectors.py
- tests/dockerfile/legacy/verify
Rescued the JupyterHub related commits out of the reverts in #130 & #131
> Fully remove jupyterhub references

- repo2docker/app.py
- repo2docker/utils.py
The `tempfile` module can take care of finding a good temporary directory
for us on platforms where `/tmp` does not exist.
Should we change the name from `git_workdir` to `workdir`? Do you care that this creates one extra level of nesting for the temporary directories?
> [MRG] Use stdlib tempfile module

- repo2docker/detectors.py
The same issue also exists in LegacyBinderDockerBuildPack(), but maybe on purpose?
> Fix binder/apt.txt detection

- repo2docker/detectors.py
Otherwise builds will throw an error if a specific version of Julia is listed in `REQUIRE`.
> RFC: Ignore "julia" in REQUIRE file when precompiling

- tests/dockerfile/binder-dir/verify
- tests/dockerfile/simple/verify
- tests/venv/apt-packages/verify
- tests/venv/binder-dir/verify
- tests/venv/postBuild/verify
Bash scripts by default continue on executing even if any
command errors. That's not the behavior we want for our scripts,
so let's explicitly get them to fail if:
1. Any command exits with non 0 exit code
2. An undefined variable is referenced
> Make all bash verify scripts fail on error

- Dockerfile
- docker/git-credential-env
and configure git to use it by default
`git-credential-env` only echoes the $GIT_CREDENTIAL_ENV environment variable when git asks for https credentials.
with this, setting GIT_CREDENTIAL_ENV="username=name\npassword=xxx" sets the credentials that will be used in clone for login-requiring endpoints (this is only when a username and password are prompted for, not all clones).
e.g.
docker run -e GIT_CREDENTIAL_ENV="username=name\npassword=xxx" jupyter/repo2docker https://github.com/private/repo
cc @drorata this is step one toward getting credentials into the build without using the token-including clone URL, which exposes the credentials inside the user containers.
To get private repo support in binderhub, we ought to only need to pass this GIT_CREDENTIAL_ENV to the build pod.
> add git-credential-env

- repo2docker/detectors.py
- repo2docker/files/conda/environment.yml
Brings in https://github.com/jupyter/notebook/pull/2959 to fix
https://github.com/jupyterhub/binderhub/issues/211
> Bump notebook version to 5.2.2

- repo2docker/detectors.py
If you don't turn on verbose updates, then I'm pretty sure the log will look
like it's hanging while it runs all the install commands under the hood. 
This adds `-v` in the call to `conda env update` which is triggered when 
`environment.yml` is found.
> Make conda env update be verbose

- .travis.yml
parallel tests might have been the cause of spurious travis failures
plus, not running concurrently should result in reusing the cache for the initial stages, which might even end up saving time
wip: waiting to see what this does on Travis
> don't run tests in parallel on travis

- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/python/freeze.bash
- repo2docker/buildpacks/python/requirements.frozen.txt
- repo2docker/buildpacks/python/requirements.txt
- repo2docker/buildpacks/python/requirements2.frozen.txt
follow-up to #156
- sync conda versions with venv pins
- update ipywidgets to 6.0.1
- fix freeze.bash so it runs on macOS (freeze happens in docker)
Specifically not included yet: freezing conda. I'd like to do that in another PR.
> update venv freeze and conda versions

- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
- repo2docker/buildpacks/legacy.py
- repo2docker/utils.py
- tests/memlimit.py
- tests/memlimit/.gitignore
- tests/memlimit/dockerfile/Dockerfile
- tests/memlimit/dockerfile/postBuild
- tests/memlimit/non-dockerfile/postBuild
This prevents builds from gobbling all the RAM on a node!
> Set limits for how much memory docker build can use

- README.md
- docs/source/faq.md
- docs/source/index.rst
- docs/source/install.rst
- docs/source/samples.rst
- docs/source/usage.rst
This is a general pass at improving the r2d documentation. It fleshes out a lot of the sections on the sphinx site, and links to this site from the README file. It covers more of usage and installation, and provides more information about the configuration files. LMK!
This touches
#146 
#114 
#103 
#73 
#113 
**NOTE:** We should link to the usage page here when it's up: https://mybinder.readthedocs.io/en/latest/preparing.html
> improving docs

- repo2docker/buildpacks/base.py
- tests/venv/apt-packages/apt.txt
- tests/venv/apt-packages/verify
Parsing apt.txt was only appending the last package to the list of packages to install. Fixed indentation to append all packages.
> Fix indentation causing only last line of apt.txt to be parsed

- Dockerfile
- It is currently breaking the build, since alpine does not
support binary wheels & we introduced ruamel.yaml which has
binary dependencies
- pip / python on alpine is broken wrt symlinks, making local
testing harder
> Stop using alpine base images

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/freeze.py
gets a few updates, but fixes issue with noarch wheel package that has been identified as broken.
ref: https://github.com/conda-forge/wheel-feedstock/pull/9
> refreeze conda environments

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
This broke out of the blue, causing CI to fail - see
https://github.com/jupyter/repo2docker/pull/180#issuecomment-356805582
> Refreeze conda environment

- Dockerfile
- repo2docker/app.py
- repo2docker/utils.py
- tests/argumentvalidation.py
- tests/ports.py
One question is I have removed the get random port method from repo2docker as docker-py supports assigning random ports if None is passed in the dict 
https://github.com/docker/docker-py/blob/190d95c61cc0440108de8a0c14027e72c56b6772/docker/models/containers.py#L596
Do we need to have the default run_cmd jupyter notebook started in the same port inside the container as outside? Is there are necessity for that?
Closes #100
> add ability for port mapping to work with non jupyter-workflow

- repo2docker/buildpacks/base.py
- tests/external/datasci.repos.yaml
- tests/memlimit/dockerfile/Dockerfile
- tests/venv/default/verify
- tests/venv/numpy/verify
Zesty fell out of support on Jan 13, and the packages have
started disappearing from http://archive.ubuntu.com/ubuntu/ and
other mirrors as of today. This will totally screw up our
build processes whenever it hits the mirror we use.
> Emergency Bump to artful

- docs/source/usage.rst
They output a Dockerfile that can not be used outside of
repo2docker, so are only useful as debugging aids.
Fixes #202
> Clarify that --debug and --no-build are for debugging only

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/julia.py
- repo2docker/buildpacks/python/__init__.py
- tests/venv/apt-packages/verify
This is a 'pure' refactor in the traditional sense of the word. We will
change the internals of how buildpacks are done from Traitlets
to using simple methods in classes + (possibly) inheritance,
but will not touch our tests - this should give us a high degree
of confidence that it won't change behavior. This will thus
be a straight port of current behavior from traitlets to classes,
with no new added functionality or ancillary cleanup.
See #191 for more discussion.
The two traitlets left are `name` and `components`. The former is 
used for logging and the latter for chaining `detect` methods together.
After this PR is merged, I'll make another one that replaces our
composing with simple linear inheritance. At that point, we can get rid
of both these traitlets. I wanted to make this PR be …
> Refactor (most) traitlets out of buildpacks

- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/python/requirements.frozen.txt
- repo2docker/buildpacks/python/requirements.txt
- repo2docker/buildpacks/python/requirements2.frozen.txt
Didn't add to conda, since there is currently no way to add
pip packages to our conda frozen setup (due to
https://github.com/conda/conda/pull/6438).
This means nteract will be available only when used with
requirement.txt, and not when used with environment.yml files.
> Add nteract jupyter extension to requirements.txt based setups

- repo2docker/buildpacks/conda/__init__.py
- tests/conda/binder-dir/binder/environment.yml
- tests/conda/binder-dir/verify
Minor parsing error identifying Python version caused Python 3.5 to be identified as Python 3 (and thus ends up using the default of 3.6).
Updates one of the conda tests to ensure that Python 3.5 is tested.
> Fix Python version detection for conda

- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/docker.py
- repo2docker/buildpacks/julia.py
- repo2docker/buildpacks/legacy.py
- repo2docker/buildpacks/python/__init__.py
- This is much cleaner to understand than traitlets
- Remove 'name' and 'component' traitlets
Depends on #206 
After this, only thing left to do is figure out what to do about LoggingConfigurable.
> Use inheritance to define composed buildpacks

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
- repo2docker/buildpacks/conda/install-miniconda.bash
via pip
Removes workaround for conda env export bug by updating conda to 4.4 in the freeze container.
equivalent of #200 for conda
> add nteract-on-jupyter to conda

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/python/requirements.frozen.txt
- repo2docker/buildpacks/python/requirements.txt
- repo2docker/buildpacks/python/requirements2.frozen.txt
This brings `nteract_on_jupyter` up to date. When I did this build I noticed it created these (untracked) files as well:
```
repo2docker/buildpacks/conda/environment.py-3.5.yml
repo2docker/buildpacks/conda/environment.py-3.6.yml
```
I don't need to add those do I?
> pin nteract_on_jupyter to 1.4.0

- .travis.yml
This helps us catch issues with MANIFEST.in and friends that
might cause problems with files not being included in the final
built package, removing a step from the release process.
> Install from wheel when testing in travis

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/python/requirements.frozen.txt
- repo2docker/buildpacks/python/requirements.txt
- repo2docker/buildpacks/python/requirements2.frozen.txt
Upgrades us to jupyterlab 0.31.5 and notebook 5.4.0.
> Bump jupyterlab and jupyter notebook to latest versions

- repo2docker/app.py
rather than instantiating all buildpacks ahead of time, only instantiate as needed.
Makes it a little clearer that a given BuildPack should only perform a single build and a new BuildPack should be created for a subsequent build.
> do not reuse BuildPack instances

- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
- repo2docker/buildpacks/legacy.py
- tests/conftest.py
- tests/venv/default/verify
supports adding arbitrary build steps to the end of Dockerfile
this enables some discussed features like Binder-deployment-specific appendices to images (e.g. enabling the nbmelt extension to shutdown notebooks that don't get used after a shorter timeout than the existing 10 minute idle timeout).
> add appendix

- repo2docker/buildpacks/base.py
- tests/memlimit.py
- tests/venv/postBuild/README.rst
This is hard for windows users and from the GitHub UI,
and provides dubious benefits. So let's remove the requirement!
Fixes #240
> Do not require postBuild to be executable

- docs/source/design.md
`reop2docker` -> `repo2docker`
> Fix typo in docs

- repo2docker/buildpacks/conda/__init__.py
there is so much verbose output that it seems to make it even harder to see what's happening, except in very particular cases.
while it's useful for debugging purposes when things like post-link fail, I don't think we should do it by default.
added a `conda list` at the end to see what's been installed
> remove -v from conda env update

- repo2docker/buildpacks/r.py
Fixes #237 
This makes sure our base R install (used by the notebook kernel) and
RStudio share the same packages.
Any ideas how we could test that this worked? I would copy the existing R test but don't know how to run the `verify` command in RStudio.
> [MRG] Setup R libraries path for RStudio

- docs/source/conf.py
Currently, the file `tests/venv/postBuild/README.rst` is missing a newline at the end of the last line, and so [samples.html](https://repo2docker.readthedocs.io/en/latest/samples.html) in the generated docs fails to properly format the `File: postBuild` heading. This fixes the code in `docs/source/conf.py` to add an extra newline Just In Case.
> make sure there's a newline before each 'File: ' heading

- repo2docker/buildpacks/docker.py
using a custom Dockerfile means opting out of *all* repo2docker logic
prompted by discussion in https://github.com/jupyterhub/binderhub/pull/459
> omit appendix on custom Dockerfiles

- repo2docker/buildpacks/r.py
This assumes apps are in ~/ShinyApps/. For now this can be seeded by
postBuild, but a better convention is to specify remote app locations in
something like a shinyapps.txt file.
> Add shiny-server.

- repo2docker/buildpacks/base.py
adding unzip to base packages so you can just run unzip on the terminal (closing https://github.com/jupyter/repo2docker/issues/251)
> Adding unzip to base packages

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/r.py
This PR aims to replace all "raw" file path accesses with calls to `binder_path(path)` which checks if the file exists in the `binder/` subdirectory.
> Fix detecting dependency files in binder/ subidr

- docs/source/design.md
- docs/source/dev_newbuildpack.md
- docs/source/index.rst
Closes #201.
- Adds missing architecture item to table of contents.
- Reorders contents to group user docs before developer docs.
- Add into sentence to design doc.
> Add doc for new buildpacks

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/buildpacks/julia.py
- repo2docker/utils.py
- tests/argumentvalidation.py
Partially addresses #211
Covers repo2docker application files:
- `app.py`
- `utils.py`
- `__main__.py`
And `JuliaBuildPack`
> Add docstrings and minor style fixes for application files and JuliaBuildPack

- .codecov.yml
- CONTRIBUTING.md
Trying to work out why we don't have the codecov bot commenting on PRs. We upload [reports](https://codecov.io/gh/jupyter/repo2docker) but don't have the bot comment. I guess it is because it is disabled for the jupyter team?
This is inspired by the comments in #277: if we want to increase coverage (I think we want to) we should make the number a bit more visible. Having the bot comment works well for me. Even better is having the browser extension installed but my assumption would be that most contributors don't have it (and it doesn't work in Firefox anymore :( )
WDYT?
> Add codecov configuration to enable PR comments

- repo2docker/buildpacks/python/__init__.py
Bulidpacks consider now two options to enable Python 2: runtime.txt with and without requirements.txt and for Python 3 it is only needed requirements.txt, runtime.txt can be included or not.
closes #280
> Enables Python2 just with runtime.txt file

- .gitignore
- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/python/requirements.frozen.txt
- repo2docker/buildpacks/python/requirements.txt
- repo2docker/buildpacks/python/requirements2.frozen.txt
Upgraded `nteract_on_jupyter`.
I also took the liberty of gitignoring the conda built outputs that are not tracked (according to https://github.com/jupyter/repo2docker/blob/master/CONTRIBUTING.md#conda-dependencies).
> update nteract_on_jupyter to 1.6.0

- .travis.yml
Enables travis retry to reduce number of times we need to manually restart tests. It feels like most of the test failures that need restarting are related to network issues.
> Use travis_retry to run tests

- repo2docker/buildpacks/base.py
Hi, `repo2docker` throws `./postBuild: Text file busy` error with Docker version 1.13.1 if there is any postBuild file in repo. This problem is docker related, I don't get the same error when I use Docker version 18.03.0-ce. Splitting docker command fixes it.
> split  post build script command in Docker file

- CONTRIBUTING.md
This adds a few guidelines/references on what to think about when merging work.
I am not a big fan of hard rules for this, so these are more like guidelines/written down version of what most of us do most of the time anyway. It also makes explicit/shares with others things like `git log --merges --pretty=format:"%h %<(10,trunc)%an %<(15)%ar %s" <deployed-revision>..` which I use to work out what hasn't been deployed yet. My hope is that others find it useful and to encourage merge-commits that make using that snippet easy ;)
> Add guidelines on merging work

- repo2docker/buildpacks/legacy/__init__.py
`_nb_ext_conf` adds configuration that requires `nb_conda_kernels`, which has been removed, preventing launch.
This means that currently, legacy images cannot launch.
> remove _nb_ext_conf from legacy env

- docs/source/usage.rst
This may be useful to DockerSpawner users who want to create custom images using repo2docker
> Add DockerSpawner command in JupyterHub config

- repo2docker/utils.py
__TraitError__ is used on lines 259 and 266 but it is neither imported nor defined which will cause a __NameError__ to be raised instead of a __TraitError__.
flake8 testing of https://github.com/jupyter/repo2docker on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./repo2docker/utils.py:259:19: F821 undefined name 'TraitError'
raise TraitError(
^
./repo2docker/utils.py:266:19: F821 undefined name 'TraitError'
raise TraitError(
^
2     F821 undefined name 'TraitError'
2
```
> from traitlets import TraitError in utils.py

- repo2docker/app.py
This pull request will add a `--version` option to the jupyter-repo2docker client, so the user can do:
```bash
$ jupyter-repo2docker --version
v0.5+234.g5c263a9.dirty
```
Since the repo and cmd are required arguments (and it would get angry without them) the easiest way to do this is to check for `--version` in the arguments **before** it's parsed by the argparser. The other way I've done is to have subcommands, but that would require a large change to the user interaction (and I don't think necessary). This will close #349
> [MRG] Add version argument

- docs/source/usage.rst
The data science handbook build has been broken for a while and users
end up with an error while following our documentation.
> Switch from PyDataScienceHandbook to Pytudes

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
- repo2docker/buildpacks/conda/install-miniconda.bash
gets notebook 5.6, which includes fixes that blocked 5.5 in #325
A subsequent PR (@GladysNalvarte is working on this) can set the display_url so that it's guaranteed to be correct when run in repo2docker, which has never been the case before.
> bump versions and refreeze

- repo2docker/buildpacks/conda/install-miniconda.bash
- tests/external/reproductions.repos.yaml
this file records transactions and seems to result in effectively turning the initial env install into a restrictive pinning, which we do not intend.
Adds xeus-cling@0.4.5 to external tests, since this repo cannot be built due to this effective pinning, but seems to build after removing the history file. It's very weird, and I'm not sure if it's intended behavior of conda or not.
cc @SylvainCorlay
> remove conda-meta/history

- docs/source/config_files.rst
A recent PR broke the importing that we were doing in the Binder docs for the "configuration files" page. Since then, the [preparing a repo for binder](https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder) page has been serving a 404 error.
This PR updates the "header" characters so that it can be properly imported again.
Done in conjunction with https://github.com/jupyterhub/binder/pull/109
> adding message and changing header characters for config files

- .travis.yml
The current travis setup uses my personal PyPI credentials. This PR switches to using the mybinderteam account.
After this we can retry auto-deploying to PyPI which currently fails because my PyPI password has changed.
> Change PyPI deploy account to mybinderteam

- docker/git-credential-env
sh is not consistent in its support of the echo builtin's -e flag. On
debian sh is symlinked to dash, which does not support the flag
resulting in bad credential output. Unfortunately /bin/echo is also
nonstandard - e.g. on macs -e is not supported while it is on debian. I
think the best approach is to rely on bash's echo builtin which should
be consistent across systems (at the slight cost of requiring bash as a
dependency)
This solves issue #388
> Issue #388 - Use bash echo for git-credential-env

- repo2docker/buildpacks/base.py
The compilation of a very simple example with a start
script in the main folder was failing (see #399)
because the `start` script was not found.
Most probably, the reason is that the folder in which
the script resides is not in the PATH. To solve this,
we replace the `start` string with a relative `./start`,
which solves the problem and completes the build and the
run.
This fixes #399
> Fix relative location of the start script

- docs/source/faq.md
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
- tests/conda/py37/environment.yml
- tests/conda/py37/verify
- bump jupyterlab to a version packaged on py37 (this is the main change that's required)
- add 3.7 to freeze list
- specify nbconvert 5.4 to avoid falling back to 5.3 in order to get pandoc 2.x (which doesn't work)
cc @allisons who reported Python 3.7 not working on the jupyterhub/binder gitter
> Support python 3.7

- repo2docker/buildpacks/julia.py
- repo2docker/buildpacks/julia/__init__.py
- repo2docker/buildpacks/julia/install-repo-dependencies.jl
- tests/julia/julia_version-1/README.rst
- tests/julia/julia_version-1/REQUIRE
- tests/julia/julia_version-1/verify
- tests/julia/julia_version/README.rst
- tests/julia/julia_version/REQUIRE
- tests/julia/julia_version/verify
This PR adds the option to specify a julia version in the REQUIRE file, and updates the JuliaBuildPack to support julia v0.7 and v1.0.
It also bumps the default julia version from v0.6.0 to v0.6.4 (the latest release for v0.6).
Adds tests for specifying a custom version, both for a `julia 0.6.3` and `julia 1`.
> Julia v1.0 support: Add option to specify julia version in REQUIRE

- docs/source/config_files.rst
- docs/source/howto/languages.rst
Some minor documentation fixes:
- avoid nested inline markup, which is not supported by Sphinx
- remove / change some strong emphasis to a admonition
> Fix documentation: avoid clashing markup

- repo2docker/app.py
- tests/test_clone_depth.py
To speed up cloning a repository, a shallow clone containing just the
last commit can be made, but *only* if no refspec is provided.
> Speed up cloning by using a depth of 1 if there is no refspec

- docs/source/faq.md
- repo2docker/app.py
- tests/conftest.py
- tests/dockerfile/editable/Dockerfile
- tests/dockerfile/editable/README.rst
- tests/dockerfile/editable/change.sh
- tests/dockerfile/editable/verify
- tests/test_editable.py
This adds an option to run from a local repository in edit mode, where
changes in a running Docker container (for example, through a
notebook) are reflected in the local repository.
Implements the feature suggested in #357.
> Add an edit-mode option

- CHANGES.rst
- CONTRIBUTING.md
Adds an initial (template) change log, with a description on its usage
in the CONTRIBUTING documentation.
> Add a change log

- docs/source/_static/custom.css
- docs/source/conf.py
This removes underlines from H2 headers that are links, and feel obnoxiously out of fashion with other headers.
It is mainly a suggestion, to scratch an itch of mine on the [configuration page](https://repo2docker.readthedocs.io/en/latest/config_files.html#id5). 
The `contents::` directive seems a bit out-of-sync with the `toctree::`, since the latter doesn't let headers link back (admittedly, that is not necessary, since that would be to the navigation bar, which is already there).
> Adjust css for header links

- docs/source/usage.rst
Hi, I ran into
`jupyter-repo2docker https://github.com/.../ --ref 16c6b...f1a9f` still using master and ignoring my `--ref`. 
@betatim suggested https://gitter.im/jupyterhub/binder?at=5bc05a19c7bf7c3662f9e0bf to 
```
have you tried changing the order of the arguments repo2docker --ref 16c...1a9f https://github.com/... we've had issues with the arguments after the URL being interpreted as the command to run in the container
```
which indeed fixed the issue. I am here updating the usage.rst document, where I got the ordering from. Not sure if that is the only documentation showing this order, and also not fixing the issue mentioned by Tim. Yours, Steffen
> Fix ordering of parameter before URL

- tests/julia/pyplot/verify
Only uses the beginning of the string to determine which version of
Python we use in Julia.
In recent builds the Julia tests fail because they use the full path to the Python shared library to determine where Python is coming from. Recently that path has become `/srv/conda/lib/libpython3.6m.so.1.0 ` which fails the strict equality test. Instead we now only check for the beginning of the path.
> [MRG] Only check beginning of name of Python shared library

- docs/source/config_files.rst
This fixes a broken link. The URL was missing a "/tutorials/" in the path so it goes from
```diff
$ git diff HEAD^
diff --git a/docs/source/config_files.rst b/docs/source/config_files.rst
index bcaa64a..fe3fb02 100644
--- a/docs/source/config_files.rst
+++ b/docs/source/config_files.rst
@@ -177,5 +177,5 @@ With Dockerfiles, a regular Docker build will be performed.
.. note::
If a Dockerfile is present, all other configuration files will be ignored.
-See the `Advanced Binder Documentation <https://mybinder.readthedocs.io/en/latest/dockerfile.html>`_ for
+See the `Advanced Binder Documentation <https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html>`_ for
```
> Correct url of Advanced Binder Documentation link

- .travis.yml
Follow up on #432 that changes back into the main repository directory so that deploy steps work.
> [MRG] Change back into main repository directory

- repo2docker/app.py
- repo2docker/utils.py
- tests/test_clone_depth.py
- tests/test_subdir.py
Using a repository that contains invalid instructions in the root of the
repository so that the test for subdirectory support will fail if
repo2docker doesn't actually switch into the requested sub-directory.
Follow up to #413 
This PR grew a bit because traitlets uses `os.getcwd()` when trying to load config files. The test run after `test_subdir` would find itself in a working directory that didn't exist anymore. As a result I added the `chdir()` context manager.
> [MRG] Switch repository used to test sub-directory support

- CONTRIBUTING.md
- README.md
- docs/source/contributing/roadmap.md
- docs/source/index.rst
Closes #462 
Taking onboard the comments about non-discoverability of GitHub issues so this is now a page in the contributing guide.
The discussions in the roadmap related issues have focussed on the way to present it and so far no comments have been received about the content. I think this means we should get rolling with this and see what happens. Discussion in this PR should hence focus on the presentation and not the content.
I added a "will be reviewed by 1st December" as an arbitrary date by which we should revisit the roadmap. Maybe by then we can work out a process for doing so.
Docs preview https://15-90722372-gh.circle-artifacts.com/0/html/contributing/roadmap.html
> [MRG] Add a first roadmap

- setup.py
If you accidentally try to install using Python 2 you get this error:
```python
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/nokome/nokome/repo2docker/setup.py", line 5, in <module>
with open('README.md', encoding="utf8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
Ideally, the user would be asked to use Python 3. If you remove the `encoding` argument, and try again then `pip` gives us this, more informative message:
```bash
$ python -m pip install -e .
Obtaining file:///home/nokome/nokome/repo2docker
jupyter-repo2docker requires Python '>=3.4' but the running Python is 2.7.12
```
This little PR implements a similar behaviour, whilst also reading the README …
> Ensure Python3 before reading README with encoding arg

- repo2docker/buildpacks/base.py
Currently a *lot* of our log info is from apt packages being
installed, and package lists being updated. This is mostly not
very useful information to users. The following outputs are
hidden:
- apt-get update, purge & clean
- apt-get installs for base packages
When there is any error from any of the apt-get steps, they will
be printed. Any packages the user explicitly lists (via apt.txt)
will have their install status messages output.
> Make apt be quieter

- repo2docker/app.py
- repo2docker/contentproviders/base.py
- repo2docker/contentproviders/git.py
Content providers can specify a "content ID" which is used to identify
versions of the content. The ID is used in the docker image name and if
we find an existing image for a given content ID the build step is
skipped.
(This is also physics @ctb 😀)
Closes #452
> [MRG] Start reusing existing docker images if content hasn't changed

- repo2docker/app.py
- repo2docker/contentproviders/base.py
- repo2docker/contentproviders/git.py
Reverts jupyter/repo2docker#461
This was causing the --image-name parameter to be ignored,
due to unconditional setting of `output_image_spec` in `fetch`.
> Revert "[MRG] Start reusing existing docker images if content hasn't changed"

- docs/source/contributing/roadmap.md
I've updated the roadmap to remove things which are done, add new things, etc.
There are more discussions in https://discourse.jupyter.org/t/repo2docker-roadmap-review/249 that can be added or lead to changes. As the roadmap is a living document I don't think we should wait for all discussions to come to an end and instead incrementally update it.
Preview: https://78-90722372-gh.circle-artifacts.com/0/html/contributing/roadmap.html
> Update the roadmap

- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
- repo2docker/buildpacks/legacy/__init__.py
- tests/test_cache_from.py
This lets us explicitly specify images that repo2docker
should try to re-use cached layers from. Docker normally only
looks for layers from images that were *built* locally - if
we want it to look in images that were *pulled* from a registry,
we need to specify it here.
This isn't a problem on binder, since we don't pull images from
elsewhere yet. However, this *is* a problem for hubploy, and
would make the life of https://github.com/yuvipanda/hubploy/pull/4
much easier.
> Allow specifying images to reuse cache from

- repo2docker/app.py
Otherwise there's no useful info printed on completion when 
you are pushing from a local install.
> Log a 'success' message when push is complete

- .travis.yml
- travis/travis-script.bash
creates jupyter/repo2docker:0.7.0 when we release 0.7.0
we have to manually tag images for past releases
> push tagged images on travis

- CHANGES.rst
- repo2docker/app.py
- repo2docker/buildpacks/base.py
- tests/test_labels.py
This PR adds repo2docker version, repo URL, and ref labels to the generated Dockerfile
Closes #466
> Add repo2docker Dockerfile labels

- repo2docker/buildpacks/base.py
When you run repo2docker locally, the uid is usually set
to the current user's uid. However, when we push the content
to Docker, we invariably set the uid of the scripts we
use as part of repo2docker at 1000. This causes a cache bust
every time.
This patch uses the correct uid, and fixes cache busting. Makes
local test runs *much* faster.
Fixes #508
> Fix cache-busting when running tests locally

- readthedocs.yml
I saw the current readthedocs [build is failing](https://readthedocs.org/projects/repo2docker/builds/8289685/). Looks like it's due to the changes made in #515. The issue is that `repo2docker` isn't installed in the readthedocs virtualenv where the documentation is being built, so we're getting an `ImportError` when trying to build the command line API documentation:
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/repo2docker/envs/latest/lib/python3.5/site-packages/sphinxcontrib/autoprogram.py", line 120, in import_object
mod = __import__(module_name)
ImportError: No module named 'repo2docker'
```
After reading through the readthedocs YAML configuration docs, I think we need to set `setup_py_install` to be `true` in `readthedocs.yml` (ref …
> Update RTD to install repo2docker

- repo2docker/buildpacks/base.py
`apt-get install` calls `dpkg` underneath to do the
installation. Unfortunately, `-qq` does not get passed
through, and we end up with a lot of log output even with
`-qq`. Redirecting stdout to /dev/null stops this output.
Errors come out to stderr, so those will be displayed.
> Make apt-get install be quiet

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
this is just the bump in #514 without the test
> refreeze with notebook 5.7.4

- .travis.yml
it should build master and tags on this repo. #499 wasn't quite right.
`on` conditions only fire when they are *all* met, which was it's a tag *and* it's the master branch, which is never true. Use `if` instead for a proper boolean condition.
> fix push-tags condition

- repo2docker/app.py
- repo2docker/contentproviders/git.py
- tests/unit/test_args.py
This PR removes f-strings from `repo2docker`
There are a few f-strings in the codebase that are causing the RTD build to fail because the docs are currently built with Python 3.5, while f-strings weren't added until 3.6 (ref https://readthedocs.org/projects/repo2docker/builds/8291787/). I was able to reproduce the f-string related `SyntaxError` when building the docs locally on `master` in a Python 3.5 environment. With the changes in this PR, the docs were successfully built locally with Python 3.5.
> Remove f-strings

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/nix/install-nix.bash
- tests/conftest.py
- tests/venv/repo-path/README.rst
- tests/venv/repo-path/extra-args.yaml
- tests/venv/repo-path/verify
- tests/venv/usr-bin/verify
We want to put the repo somewhere other than ${HOME}
so we can mount persistent storage in ${HOME} more easily.
Most of repo2docker assumes current directory is where
the contents are, so we should be able to get most of it
working by setting WORKDIR to ${REPO_PATH} and letting
${REPO_PATH} be configurable.
Unclear what to do for plain Dockerfiles, Legacy Dockerfiles &
nix.
> Copy repo to ${REPO_DIR} rather than ${HOME}

- hooks/post_push
truncate to 8 characters correctly
> fix commit hash truncation on docker images

- tests/unit/test_connect_url.py
Instead of installing the normal stack just install the notebook server
and launch it to check for the launch URL being output correctly.
`Dockerfile` comes from Min's https://github.com/binder-examples/minimal-dockerfile/
> Use a minimal hand-crafted Dockerfile for speed

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/contentproviders/base.py
- repo2docker/contentproviders/git.py
- tests/conftest.py
- tests/unit/contentproviders/test_git.py
- tests/unit/contentproviders/test_local.py
- tests/unit/test_app.py
- tests/unit/test_memlimit.py
- tests/unit/test_subdir.py
> [MRG] Add caching of already built repositories

- repo2docker/app.py
- repo2docker/utils.py
- tests/unit/test_argumentvalidation.py
- tests/unit/test_utils.py
Wanted to quickly add some tests for the port mapping function and then ended up rewriting it.
I tried to follow https://docs.docker.com/config/containers/container-networking/#published-ports because I've never used a port mapping more complex than `8888:8888`.
> [MRG] Add tests for port mapping conversion

- Pipfile
- dev-requirements.txt
- docs/source/contributing/contributing.md
Proposed fix for https://github.com/jupyter/repo2docker/issues/548.
I'm not sure that this is the right solution here, but pinning the pytest version does work.  It may make sense to pin to a later version.  
Included a change to fix a Sphinx documentation build error apparently caused by recent changelog changes.
> Fixes Travis build errors related to pytest and Sphinx 

- docs/source/howto/lab_workspaces.rst
- docs/source/howto/user_interface.rst
- docs/source/index.rst
This does the following:
* updates the interfaces page to give more useful information.
* Adds a section on Nteract and Shiny
* Adds a page about packaging workspaces for JupyterLab
* Does some minor re-structuring on the index page to make the content more discoverable (trying to riff off of @yuvipanda 's TLJH docs)
If we merge this in, then we should also update `conf.py` in the Binder docs repository to pull the JupyterLab workspaces page into the build: https://github.com/jupyterhub/binder/blob/master/doc/conf.py#L172
> updating interfaces page and adding jupyterlab workspaces page

- docker/git-credential-env
- tests/unit/test_docker.py
echo without quotes removes newline, echo with quotes preserves it.
Previously failing test added.
I believe this is needed to deploy BinderHub with private credentials (cc @sgibson91 who's looking at this)
> missing quotes in GIT_CREDENTIAL_ENV

- repo2docker/buildpacks/python/__init__.py
We are experiencing issues with mybinder for this repo: https://github.com/NSLS-II/tutorial due to https://github.com/pypa/pip/issues/6197:
```py
Exception:
Traceback (most recent call last):
File "/srv/conda/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
status = self.run(options, args)
File "/srv/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 346, in run
session=session, autobuilding=True
File "/srv/conda/lib/python3.6/site-packages/pip/_internal/wheel.py", line 886, in build
assert have_directory_for_build
AssertionError
Removing intermediate container b42459fcd7a3
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 2Error during build: …
```
> FIX: a temporary workaround for pip-19.0.1 issues

- repo2docker/buildpacks/base.py
- tests/venv/postBuild/postBuild
- tests/venv/postBuild/verify
- defines NPM_DIR env and creates it at APP_BASE/npm
- tells npm to use this dir for `npm install --global`
closes #307
Related to #25, but not closing since this doesn't introduce package.json support or similar.
> npm installation

- repo2docker/buildpacks/conda/install-miniconda.bash
- tests/conda/binder-dir/verify
even with auto-update-conda disabled, switching Python version (which reinstalls conda) can end up upgrading to the latest conda
Avoid this by adding the conda pinning to that install stage
This should fix the recent failures on CI, which appear to be due to a bug in the recent conda 4.6
> pin conda during Python-switch step

- repo2docker/app.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
- repo2docker/buildpacks/legacy/__init__.py
- tests/unit/test_app.py
- tests/unit/test_cache_from.py
Includes extra kwargs to limit CPU quota when building and running a docker image.
Closes #459
> Exposes CPU limit

- .travis.yml
running pip freeze on every test is super helpful for debugging when a dependency change starts causing test failures
and stop building docs on travis; we are building them on circle now
> add pip freeze to travis.yml

- docs/source/install.rst
This came in handy for me, to get the fixes for the python3.5 compatibility. Might be helpful for others, too.
> install: one-liner to install most recent upstream code

- docs/source/config_files.rst
- docs/source/faq.rst
- docs/source/index.rst
- docs/source/usage.rst
This adds a few additional cross-references, mentions Python 2.7 support and removes a level from the TOC for How To guides inn the index.
> [MRG] Update documentation with more cross references

- repo2docker/utils.py
`[:xdigit:]` is not a valid character class in Python regular expressions
use explicit hex digit pattern
> fix "Possible nested set" warning

- docs/source/changelog.rst
Originally thought we hadn't changed much so the next release would be 0.7.1.
However while collecting things for the change log I changed my mind. There are quite a few changes, most in the "making things more stable and reliable and conformant" department. Should we call it 0.8.0?
Please make suggestions about the wording for the change log via the GitHub UI. Not quite sure what tense/form they should take.
> [MRG] Update ChangeLog to release 0.8.0

- repo2docker/buildpacks/conda/freeze.py
- tests/unit/test_freeze.py
Some tests to increase coverage of our `freeze.py` script. Tests the `set_python` function.
> [MRG] Add tests for setting Python version during freeze

- docs/source/faq.rst
- docs/source/howto/export_environment.rst
- docs/source/index.rst
This adds a FAQ entry and a short how-to guide to explain how a user can get a strict export of their conda environment that will work in repo2docker even if they use OSX or Windows as their operating system.
I also created https://github.com/binder-examples/conda-freeze as a "base" conda env people can use. The goal is that it installs nothing extra but triggers the conda build pack.
This is in response to https://github.com/jupyterhub/binder/issues/149 and https://github.com/jupyterhub/mybinder.org-deploy/issues/906 which both had problems with this.
> [MRG] Add FAQ entry and Howto on exporting conda environments

- docs/pull_request_template.md
- docs/source/contributing/contributing.md
Add a PR template that links to two particular parts of our contributing docs that are otherwise several clicks away. It also rewords some sentences to remove the word "code".
The two things that are brought closer with this are our "guide to getting things merged" and "proposing big changes".
I think advice like "get consensus" applies to big changes to the docs just as much as for code changes. Hence proposing to remove the word code.
> [MRG] Add PR template with links to contrib docs and less focus on code contributions

- docs/source/config_files.rst
This small config documentation update follows from https://github.com/jupyterhub/binder/issues/152#issuecomment-469668454 and https://github.com/jupyter/repo2docker/issues/411#issuecomment-462487697  Clarifying how `environment.yml` is used may help future users avoid the confusion I had.
This update is based on my understanding of
https://github.com/jupyter/repo2docker/blob/e6cbf3e3a3e399508d5628b4ff1d30afed8c944f/repo2docker/buildpacks/conda/__init__.py#L178-L186
I avoided getting too technical in the documentation about the role of frozen environments.
> Expand environment.yml config notes

- docs/source/howto/languages.rst
Two doc-changes as a follow up on #595:
- update links to Pkg.jl documentation;
- change `Compat` to `[compat]` since that is usually how we refer to said section.
> [MRG] Julia: Two small doc updates

- repo2docker/buildpacks/legacy/__init__.py
- repo2docker/buildpacks/legacy/apt-sources.list
Debian Jessie is now "archived" so we need to update the links to the
sources.
This fixes the build failure we are seeing in #631.
> [MRG] Update the source links used by the legacy buildpack

- docs/source/faq.rst
- docs/source/usage.rst
The latest version of repo2docker (`0.8.0`) seems to be using Python 3.7 as the default.
This change updates the docs to reflect that.
> [MRG] Python 3.7 as the default in the docs

- repo2docker/contentproviders/git.py
- tests/conftest.py
- tests/unit/contentproviders/test_git.py
This is a continuation of #540. See that PR for details. That PR by @alimanfoo was only missing a test so this is my attempt at adding one.
Some things to note:
1. Should I merge or rebase upstream or leave this branch where it is?
2. I'm not a pytest fixture expert, but I don't think there was a cleaner way of doing what I needed to do to create the git repositories. I separated out the functionality of `repo_with_content` so I could reuse them in my new fixture.
3. After creating the fixture, I then realized there was no builtin way to get the submodule's SHA without running some commands with subprocess. It made the git unit tests uglier, but I wasn't sure what else to do.
4. As part of point 2 above, I changed the functionality of adding content to a test repository to use append so …
> [MRG] Ensure git submodules are updated and initialized

- repo2docker/buildpacks/conda/__init__.py
Investigate what happens if we delete the download cache of conda packages.
If I build https://github.com/binder-examples/conda with `master` I get an image which is 2.04GB according to `docker images` and if I build the same repo with this PR I have one that is 2GB.
@rabernat what do you use to measure the image sizes? (I've never really looked into this before).
Fixes #636
> [MRG] Remove conda download cache explicitly

- repo2docker/buildpacks/r.py
This uses an unreleased version of jupyter-server-proxy that has a fix for the broken websocket handling.
This (I think) will fix the problems reported in https://discourse.jupyter.org/t/debugging-your-binder/33/12?u=betatim
> [MRG] Fix up the server proxy package to get websockets back

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-question.md
Add issue templates for the different kinds of questions people might have.
* support questions are directed to discourse
* bug reports ask for some details about the platform, versions, etc
* feature requests contain a note that let people know that the best way to get a feature implemented is to "do it yourself". Where "do it yourself" doesn't mean "write the code" but more facilitate it by providing resources, etc. And that even then there are no promises that something will get merged because of the maintenance burden it adds.
This was sparked from a discussion with @KirstieJane about setting expectations for people opening issues.
> [MRG] Update issue templates

- docs/source/changelog.rst
- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/freeze.py
- repo2docker/buildpacks/conda/install-miniconda.bash
This bumps the miniconda version to 4.5.12 (latest) and the conda version to 4.6.11 (latest). Conda 4.6 included a number of performance improvements that should help speed up install times for complex environments. It also included some improvements to conda's interoperability with pip. An overview of the conda release is available here: https://www.anaconda.com/conda-4-6-release/.
Fixes #593
> [WIP] Bump conda version 

- docs/source/design.md
- docs/source/usage.rst
- repo2docker/__main__.py
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/nix/nix-shell-wrapper
- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/r.py
- tests/unit/test_binder_dir.py
> Support .binder directory

- repo2docker/__main__.py
- tests/unit/test_args.py
If a string of only numerals is passed as argument we assume it should
be converted to an integer and specifies a size in bytes.
When BinderHub constructs the `repo2docker` command-line it [passes a value in bytes without a suffix](https://travis-ci.org/jupyterhub/mybinder.org-deploy/builds/525264674#L1113-L1135). This is with a value of `"3G"` set in the `values.yaml`.
I think this will allow us to try out https://github.com/jupyterhub/mybinder.org-deploy/pull/954
> [MRG] Fix handling of memory limit command line argument

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
- docs/source/contributing/contributing.md
Some personal fiddling on top of @betatim's PR #654. All edits up for discussion!
Ready for review ❤️ 
Changes in this PR:
* Reformatting and added comments to `bug_report` and `feature_request` issue templates.
* Added more words around the contributing guidelines via read the docs. Some reformatting but generally a lot of the content is the same, just with a few extra bits and bobs added to make it (I hope) more accessible.
* Added more words to the links in `CONTRIBUTING.md` to try to nudge folks to go and actually read the documentation.
> [MRG] Update contributing guidelines and issue templates

- repo2docker/buildpacks/base.py
Unlike other parts of the generated Dockerfile,
the start script is evaluated at run time, rather
than at build time. Currently, we assume that the
current working directory is the same at runtime
as build time for the start script. This doesn't
hold true always, and particularly not in JupyterHub
environments where ${HOME} is often overlaid with
a persistent directory.
We change this to always refer to the full path,
using the ${REPO_DIR} environment variable. This
lets people building JupyterHub images to set
REPO_DIR to something like /srv/repo (like hubploy
does), and still have a working start script.
> Make sure ENTRYPOINT is an absolute path

- docs/source/config_files.rst
originally in description of the `start` config file it read:
"The last line must be ``exec "$@"`` equivalent." 
Seemed open to interpretation as I needed to deduce what the equivalent of that would be here. 
I think adding 'or' before 'equivalent' shows that will work, but I assume other options exist? Or why not say  "The last line must be ``exec "$@"``"?
> tweak language to make clear `exec "$@"` works

- docs/source/index.rst
- docs/source/specification.rst
- docs/source/usage.rst
This is a fairly lightweight information page that coins the term "Reproducible Execution Environment Specification" (REES), and provides a little bit of explanation for what it is. In the future, we could flesh out this page a bit more.
closes #656
WDYT @betatim ?
> specification info page

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/conda/install-miniconda.bash
This shrinks our "base" image by about 50MB plus 40MB from the second commit.
You can see the size of the "install miniconda" layer in various scenarios here:
* with `master` https://microbadger.com/images/betatim/r2d-minimal-python (330MB)
* with this PR https://microbadger.com/images/betatim/r2d-minimal-python-2 (270MB)
* before we had a separate conda env for ocnda itself https://microbadger.com/images/betatim/binder-example-requirements (218MB)
Maybe there is more saving potential somewhere, this was low hanging fruit. If someone knows a tool to see which files get created by each layer we could check for other temporary files left over that can be deleted.
> [MRG] Remove the conda package cache as we can't hardlink to it

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
- tests/memlimit/dockerfile/Dockerfile
- tests/unit/test_cache_from.py
- tests/unit/test_memlimit.py
> [MRG] Update base image used for memory limit checks

- docs/source/changelog.rst
- repo2docker/app.py
- tests/unit/test_app.py
Fixes #267 and #395. Solution suggested in https://github.com/jupyter/repo2docker/issues/267#issuecomment-478691267
> [MRG] Do not try to build the image with root as the primary user.

- docs/source/changelog.rst
- repo2docker/app.py
- tests/unit/test_app.py
Reverts jupyter/repo2docker#676
@sgibson91 tried to deploy this to mybinder.org just now and it failed. The log of the deploy job is at https://travis-ci.org/jupyterhub/mybinder.org-deploy/builds/530202815#L1117-L1138 Reverting this so we can keep deploying changes and don't have the stress of having to fix this to unblock deploys.
I think we need to extend the check from "is the user root" to "is the user root and didn't user --user-id".
> Revert "[MRG] Do not try to build the image with root as the primary user."

- docs/source/changelog.rst
- repo2docker/app.py
- tests/unit/test_app.py
This a redo of https://github.com/jupyter/repo2docker/pull/676. It errors r2d when root users try to run it without `--user-id` specified. The difference between this PR and #676 is that check is done against `self.user_id`. PTAL @betatim
> Do not try to build the image with root as the primary user

- .travis.yml
- README.md
- docs/source/changelog.rst
- docs/source/install.rst
- setup.py
This PR drops support for running repo2docker on a system that has Python 3.4 only. This does not effect users ability to build repositories that need Python 3.4
Why? One of our dependencies has stopped shipping wheels for Python 3.4 because https://www.python.org/dev/peps/pep-0429/ states that the last release of Python 3.4 was in March 2019.
There are two questions here:
* should we also drop Python 3.4 support?
* why does our travis setup not install ruamel.yaml "from source" but fail when there are no wheels? https://travis-ci.org/jupyter/repo2docker/jobs/535148903#L643
> [MRG] Drop support for Python 3.4

- repo2docker/__init__.py
- repo2docker/app.py
- tests/unit/test_users.py
`getpass` is available on windows as well as unix, whereas `pwd` is not
available on windows.
`getpass.getuser()` also looks are environment variables which means users can trivially change the value. I don't think this is a problem for us as we don't use it for access control and give users a way to set this to arbitrary values via CLI flag already.
Using this instead of `pwd` means we are a bit closer to working on Windows which is nice even though we don't officially support the windows platform. Unless there is a strong reason to I'd vote for taking the option that does not break Windows.
Not quite sure how to test this :-/
> [MRG] Use getpass instead of pwd to fetch username

- .travis.yml
This PR updates Travis CI to use Ubuntu 16.04. Fixes #685
> Switch Travis CI to Ubuntu Xenial 16.04

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/conda/activate-conda.sh
- tests/conda/default-env/postBuild
- tests/conda/default-env/verify
- tests/conda/default-env/verify.py
so that `conda install` commands affect the kernel environment instead of the base env
This should preserve `conda install` behavior for Dockerfiles that inherit from r2d images.
This behavior is already managed at runtime by the ENTRYPOINT which properly activates the env.
cc @tam203 who reported the issue on gitter
I'm still testing this locally, and trying to think of a reasonable way to include an automated test for this.
> set CONDA_DEFAULT_ENV

- tests/base/node10/verify
Instead of checking the minor version as well only check the major version of npm.
This recently broke because the version that gets installed now is 6.9 not 6.4 any more.
> [MRG] Update verification of Node install

- docs/source/architecture.md
This adds mention of the ContentProvider class in the "architecture" page (that currently explains what BuildPacks are. I imagine that this information might be incomplete or maybe even incorrect, so it would be great if @betatim and @pdurbin could give their own edits or comments.
This might close #444 if we're happy enough with the information.
> Adding contentprovider documentation

- docs/source/index.rst
- docs/source/usage.rst
- repo2docker/app.py
- repo2docker/contentproviders/__init__.py
- repo2docker/contentproviders/zenodo.py
- repo2docker/utils.py
- tests/conftest.py
- tests/external/reproductions.repos.yaml
- tests/unit/contentproviders/test_zenodo.py
The goal of this PR is to make `repo2docker 10.5281/zenodo.3229823` work.
related: #234, #102
> [MRG] Zenodo content provider

- Dockerfile
- tests/external/reproductions.repos.yaml
ensures clones are in-tact when there are LFS-stored files.
Test repo added at binderhub-ci-repos/lfs
I don't think the test really covers this, since I think the tests don't use the repo2docker in the image, they use the local install.
> add `git-lfs` to dockerfile used for the repo2docker image

- Dockerfile
for a much smaller image (93 vs 231 MB) and faster builds.
The issue that prevented us from using alpine (#160) has since been resolved.
> base docker image on alpine

- repo2docker/contentproviders/zenodo.py
- repo2docker/utils.py
- setup.py
- tests/unit/contentproviders/test_zenodo.py
- tests/unit/test_utils.py
Updates the Zenodo content provider to:
- Use a more general DOI -> URL conversion
- Support different hosts and different metadata organizations
My interest is supporting CaltechDATA, which is based on Zenodo but has a different metadata scheme.  I'll also work on getting Binder buttons into CaltechDATA, which would be cool.
I'm still working on figuring out how to generalize the object path stuff.  The idutils functions could also be copied into utils; don't know what your preference is on dependencies.  Any and all suggestions are appreciated!
> [MRG] Generalize Zenodo content provider to support other Invenio repositories

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/conda/install-miniconda.bash
This is a test related to #707: removing static libraries and such.
> [MRG] Remove more files during the image build to slimdown the image

- docs/source/install.rst
The install instructions pointed to an outdated link for the community edition of docker. I have updated the link to point to https://docs.docker.com/install/.
> updated link for the community edition of docker

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/r.py
Split the assemble scripts into two categories. The default one which is as it was: executed after we copy the contents of the repository. A new one that build packs can opt into: executed just before we copy the content of the repository.
I also moved when we install stencila and some other R related setup things to the build scripts as they don't depend on the contents of the repo. This way they can be shared amongst all images.
This (the pre-assemble phase) could be useful for things like `apt.txt` which depends on the content of the repo (so shouldn't go in `get_build_scripts()`) but to execute the resulting command you don't need access to the contents of the repository. A counter example would be `requirements.txt` as the resulting `pip install -r requirements.txt` could need access …
> [MRG] Install APT packages before copying the repo contents

- repo2docker/app.py
The current sentence did not indicate that other operations are possible in `target_repo_dir` as well.
See https://discourse.jupyter.org/t/users-home-in-jupyterhub/1463/3 for context.
> Update target_repo_dir docstring

- repo2docker/__main__.py
- repo2docker/app.py
- tests/unit/test_app.py
Trying to atone for bugs introduced by #679. With this PR exiting happens only when r2d is invoked from the commandline. In case user tries to use r2d as library, `ValueError` is raised instead.
> [MRG] Handle root user case more gracefully. Fixes #696

- repo2docker/contentproviders/zenodo.py
- repo2docker/utils.py
Remove a stray print statement and an unused import in the zenodo content provider.
> [MRG] Remove print statement and unused import

- tests/external/reproductions.repos.yaml
so we don't have an old env relying on the free channel
re-do of #722, gets tests passing in #719
> bump xeus-cling in tests

- Dockerfile
- docs/source/changelog.rst
Re: #736 
Since `alpine` images  don't include bash by default, this breaks the usage private repos with `git-credential-env` which requires [bash](https://github.com/jupyter/repo2docker/blob/master/docker/git-credential-env#L1).....small PR to just add bash to the `Dockerfile` (image size increased ~5MB)
> [MRG] Adding bash to Dockerfile to fix git-credential-env

- repo2docker/buildpacks/conda/freeze.py
- repo2docker/buildpacks/conda/install-miniconda.bash
- tests/conda/binder-dir/verify
Conda 4.7.5 was [released yesterday](https://www.anaconda.com/how-we-made-conda-faster-4-7/). This PR bumps the Conda version from 4.6.14 to 4.7.5. Note that a new version of Miniconda has not yet been released. I will bump that version number as well if a newer version is released before this PR is merged.
This is my first PR and I did my best to identify all possible locations where the Conda version number was explicitly specified. I only found two in `repo2docker/buildpacks/conda` directory.
> [WIP] Version bump Conda from 4.6.14 to 4.7.5

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/r.py
This is the R part of #716. Needs rebasing after #716 gets merged.
> [MRG] Install R packages before copying repo contents

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
includes fixed certifi package which solves the specific case in #725
a few package bumps, too, including ipython, jupyter_client, tornado, and zeromq
Closes #725
> refreeze 2019-07-16

- repo2docker/utils.py
must use `r` prefix when there are escapes
> typo in doi regexp

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/pipfile/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/utils.py
- tests/unit/test_utils.py
re-issue of #410 based on #716
- conda preassembles *unless* there are local pip requirements
- requirements.txt preassembles *unless* there are local refs (e.g. `-e .`)
- <del>pipenv always preassembles (may need local ref check like requirements.txt?)</del>
> [MRG] preassembly for conda/python

- repo2docker/buildpacks/r.py
- tests/unit/test_preassemble.py
Without this we don't collect the files that other build packs need to
copy them over to the container in the pre-assemble stage.
Needs a test to stop it from coming back.
closes #751
> [MRG] Call parent preassemble scripts methods

- tests/unit/test_semver.py
Rewrite tests using Pytest's [parametrizing](https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) functionality.
> [MRG] Rewrite tests in test_semver.py #615

- docs/source/config_files.rst
- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
- repo2docker/buildpacks/conda/install-miniconda.bash
- tests/base/node10/verify
- tests/conda/binder-dir/verify
This pull request modifies the conda buildpack to install `jupyterhub` and `nteract_on_jupyter` from conda-forge instead of pip. 
According to @ocefpaf "this can lead to dependencies installed with conda and cause problems. (Sometimes things just works but it is 50-50 change.)" And we are seeing this mixing currently in Pangeo environments built with repo2docker (https://github.com/pangeo-data/pangeo-cloud-federation/pull/305).
Described in detail https://github.com/jupyter/repo2docker/pull/714#issuecomment-505278413
Because we aren't changing versions here I suspect there aren't going to be issues, but let me know if I can add tests or other modifications.
> [MRG] switch pip packages to conda-forge in conda buildpack

- repo2docker/buildpacks/julia/julia_project.py
Julia 1.2.0 is released :)
I believe the julia_version-default test should now automatically test on 1.2.0 with this PR.
> Add support for Julia 1.2.0

- repo2docker/buildpacks/conda/install-miniconda.bash
This PR bumps the Conda and Miniconda versions from 4.6.14 to 4.7.10.
> Bump Miniconda from 4.6.14 to 4.7.10

- repo2docker/buildpacks/r.py
This PR upgrades IPKernel version to 1.0.2 and closes https://github.com/jupyter/repo2docker/issues/765, hopefully without breaking anything else :eyes:
> [WIP] Upgrade IRKernel version to 1.0.2

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/utils.py
- tests/unit/test_utils.py
This should fix https://github.com/jupyter/repo2docker/issues/764
Decided to use *chardet* to guess the encoding because I liked the idea of reusing the function for ``environment.yml`` also (not sure if this was the right call).
> Handle different file encodings

- Dockerfile
- hooks/post_push
so instead of `abc123` it's `0.10.0-4.abc123`
- 0.10.0 is the latest tag
- 4 is the number of commits since then
- abc123 is the hash
also should fix the presence of `dirty` in the version in our images by calling `git clean`
> include repo2docker version in docker tags

- repo2docker/app.py
for backward-compatibility, add a `layers` key with the full data,
preserving the `progress` field, which has only partial data, depending on state of each layer.
The most useful field, I think, is `progress`, which shows the docker cli-rendered progress bar.
Strangely, when I sampled the log data we get from ovh, current and total in progressDetail (which we already publish under 'progress') were on totally different scales,
so rendering our own progress bars with `$current/$total` doesn't seem trustworthy. Not sure what's up with that.
Sample log data:
```json
"layers": {
"25b373f5f7f1": {
"status": "Waiting",
"progressDetail": {},
"id": "25b373f5f7f1"
},
"e9f2b5eca21e": {
"status": "Pushing",
"progressDetail": {
"current": 747589632,
"total": 758965327
},
"progress": …
```
> include full docker progress events in push progress events

- repo2docker/buildpacks/base.py
- tests/unit/test_external_scripts.py
Fixes #673
This PR allows to provide an absolute path for source files in `get_build_script_files`. As a result, plugins can inject files outside of r2d's repository. In case, source file path is relative, the old behavior is preserved, i.e. path is assumed to be relative to the directory where `repo2docker/buildpacks/base.py` is.
@yuvipanda PTAL!
> [MRG] Allow absolute paths in build_script_files

- repo2docker/app.py
- tests/unit/test_app.py
- tests/unit/test_argumentvalidation.py
- tests/unit/test_subdir.py
> add explicit log message on failing Docker connection

- repo2docker/app.py
removes need to specify `--debug --no-build` and enables piping stdout to a Dockerfile without including logs.
`--debug` still logs the Dockerfile, but only when `--no-build` is *not* set.
That means that the Dockerfile is output at most once:
- if `--no-build`, to stdout
- if `--debug` and not `--no-build`, to the logs
> Print Dockerfile to stdout when --no-build

- azure-pipelines.yml
- dev-requirements.txt
Partially addresses #744 
- Enable Azure Pipelines
- Add minimal tests
- Azure Pipelines needed requests so adding to dev requirements
> Add baseline infra for Azure Pipelines

- azure-pipelines.yml
- tests/unit/test_env.py
- tests/unit/test_ports.py
- tests/unit/test_users.py
- tests/unit/test_volumes.py
os.getlogin apparently doesn't work everywhere (can raise OSError, inappropriate ioctl for device)
and is failing on azure pipelines tests
> use getpass.getuser instead of os.getlogin

- Dockerfile
This is an attempt to fix [the fact that the repo is still marked as dirty](https://github.com/jupyterhub/mybinder.org-deploy/pull/1151#issuecomment-529171875) because now the files are missing.
> [MRG] Restore the hooks directory when building the docker image

- docs/source/contributing/roadmap.md
- docs/source/usage.rst
- repo2docker/app.py
- repo2docker/contentproviders/__init__.py
- repo2docker/contentproviders/doi.py
- repo2docker/contentproviders/figshare.py
- repo2docker/contentproviders/zenodo.py
- tests/unit/contentproviders/test_doi.py
- tests/unit/contentproviders/test_figshare.py
- tests/unit/contentproviders/test_zenodo.py
Also needs UI update: https://github.com/jupyterhub/binderhub/issues/938
> [MRG] Add Figshare content provider

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.yml
Updated the version and refroze.
> [MRG] Update nteract-on-jupyter to 2.1.3

- docs/source/config_files.rst
- docs/source/faq.rst
- repo2docker/buildpacks/r.py
- tests/unit/test_r.py
Closes #661 
This uses the instructions from https://cran.r-project.org/bin/linux/ubuntu/README.html to allow users to select a different version of R. We use the `runtime.txt` to let users specify which version they want via `r-3.6-YYYY-MM-DD` (selects R 3.6, 3.6.1 to be precise) or `r-YYYY-MM-DD` (selects the default, currently 3.4).
We can also add support for R 3.5 but I wanted to open the PR before being done. Ideally `r-3.4-YYYY-MM-DD` should be equivalent to `r-YYYY-MM-DD` as well.
This is pretty exciting as it adds a frequently requested feature without a lot of new code.
What do people think of using `runtime.txt` like this? I like it and prefer it over trying to guess a R version from the date or introducing an additional file. Maybe in a second PR we can check if a …
> [MRG] Add support for installing different versions of R

- repo2docker/buildpacks/r.py
I think this will fix the problem we had in https://github.com/jupyterhub/mybinder.org-deploy/pull/1165
Merging without review to see if we can get it deployed and working.
> Use port 80 to download GPG keys to avoid firewall problems

- repo2docker/buildpacks/conda/install-miniconda.bash
- tests/conda/binder-dir/verify
This PR bumps the Conda version from 4.7.10 installed by most recent Miniconda release to 4.7.12 which is the most recent version of Conda itself.
4.7.12 release of Conda fixed a number of issues related to permissions that I was experiencing when using Conda + Docker on other projects.
> [MRG] Bumped conda version to 4.7.12

- repo2docker/buildpacks/r.py
Based on [this Discourse discussion with Tim](https://discourse.jupyter.org/t/widget-failing-in-shiny-app), regarding an error I have on a widget in a Shiny app, I made two small edits in r.py:
1. Updated the version of RStudio Server to the latest, stable release available on the official RStudio website (URL commented in code). This involved two code lines, namely, the URL and the MD5.
2. Updated the version of Shiny Server, too, as it could also be relevant to the present error. This involved the same types of edits as above.
Thank you!
> [MRG] Upadte RStudio 1.1 - > 1.2, minor update to RShiny

- repo2docker/buildpacks/base.py
If the Docker host does not support sparse files `/var/log/lastlog` can be extremely large if a large UID is set. `--no-log-init` prevents lastlog being created, but this requires `useradd` instead of `adduser`
closes #223
> adduser: useradd --no-log-init to reduce lastlog size

- docs/source/changelog.rst
- repo2docker/contentproviders/git.py
- tests/conftest.py
- tests/unit/contentproviders/test_git.py
This should fix https://github.com/jupyterhub/binderhub/issues/997.
Should I add a test?
> [MRG] Fix submodule check out

- repo2docker/contentproviders/git.py
This is a follow up to #809 to see if we can remove the explicit checkout command which causes big scary warnings about "detached head" mode.
> [MRG] Remove explicit checkout when ref given

- docs/source/architecture.md
- docs/source/contributing/buildpack.md
- docs/source/contributing/contentprovider.rst
- docs/source/contributing/contributing.md
- docs/source/contributing/index.rst
- docs/source/contributing/roadmap.md
This does two things:
1. Adds some short instructions for extending repo2docker to a new ContentProvider
2. Updates some of the section titles in this section in order to make the sidebar easier to parse (having the word "repo2docker" in each page title seemed redundant and cluttered the sidebar)
This is related to https://github.com/jupyterhub/binderhub/pull/1017. Eventually the two docs should probably reference one another, as adding a new RepoProvider in BinderHub is often paired with adding a new ContentProvider in repo2docker. This also makes me wonder why it's called "RepoProvider" in one and "ContentProvider" in another...
> adding instructions for contentprovider extension

- repo2docker/buildpacks/r.py
https://github.com/jupyterhub/mybinder.org-deploy/issues/1308 is reproducible when running manually:
- `docker run -it --rm ubuntu:18.04`, install base dependencies `apt-get install -y gnupg ca-certificates`
- Setup PPA https://github.com/jupyter/repo2docker/blob/f79bf04a410b1482eb8e7d0e8369e2ba6c5467f4/repo2docker/buildpacks/r.py#L236 https://github.com/jupyter/repo2docker/blob/f79bf04a410b1482eb8e7d0e8369e2ba6c5467f4/repo2docker/buildpacks/r.py#L244
- Install `3.6.1-3bionic` https://github.com/jupyter/repo2docker/blob/f79bf04a410b1482eb8e7d0e8369e2ba6c5467f4/repo2docker/buildpacks/r.py#L78
```
root@abc76a08c669:/# apt-get install r-base=3.6.1-3bionic r-base-dev=3.6.1-3bionic libclang-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some …
```
> [WIP] r build-pack: when using ppa install r-recommended

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/julia/julia_require.py
- tests/base/node10/verify
- jupyterhub 1.1 (includes #832)
- notebook 6
- nbconvert 5.6
- jupyterlab 1.2
- widgets 7.5
switch to new jupyterhub-base package which doesn't depend on unused configurable-http-proxy and node.js, and should reduce confusion about two nodes being installed. I think this fixes recent CI failures associated with a newer release of node on conda-forge.
> [MRG] update base environment

- docs/source/config_files.rst
This may be obvious in hindsight, but it's easy to forget since problems anywhere else will abort the build.
> docs: postBuild warn about shell script errors being ignored

- repo2docker/buildpacks/conda/install-miniconda.bash
This adds the offlinenotebook extension to the base install. With this
users can download their notebook even after the server has gone away.
The extension came out of ideas in https://github.com/jupyterhub/binderhub/issues/1003.
I think we should give this a try and see what people say to it. You can demo it on https://github.com/manics/jupyter-offlinenotebook (has a binder link).
> [MRG] Add jupyter-offlinenotebook extension

- .pre-commit-config.yaml
In https://github.com/jupyter/repo2docker/pull/848 I ran into problems with black auto-formatting some new code in a way that incompatible with Python 3.5 (I think this issue is related: https://github.com/psf/black/issues/419).
It looks like this is fixed in the latest black.
> [MRG] Update black 19.10b0, target Python 3.5

- repo2docker/utils.py
- tests/unit/test_utils.py
Extracted from #806 
Older versions of Podman occasionally failed to terminate their output with a newline. This resulted in a bug due to `execute_cmd` not flushing the final line of the buffered stdout if it didn't end with a newline.
Current versions of Podman seem to work without this fix, however if repo2docker is further extended in future it would be good to avoid someone else hitting this bug.
> [MRG] utils.execute_cmd flush buffer if no EOL

- repo2docker/buildpacks/r.py
- tests/unit/test_r.py
Related to https://github.com/jupyter/repo2docker/issues/773#issuecomment-586571022
The particular issue I ran into today is a missing "latest" MRAN snapshot in the Travis R tests. This PR automatically tries older snapshots in this case.
What's not clear to me from the linked issue is whether the test failures mostly occur due to a missing latest snapshot (this PR should help), or whether it's due to a broken MRAN server for a snapshot that definitely exists.
Example:
```
$ repo2docker tests/r/description-file/
Picked Local content provider.
Using local repo tests/r/description-file/.
Failed to get MRAN snapshot URL https://mran.microsoft.com/snapshot/2020-02-13: 404 Not Found
Using RBuildPack builder
```
> [MRG] If looking for latest MRAN URL try earlier snapshots too

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/conda/install-miniforge.bash
- tests/conda/binder-dir/verify
[miniforge](https://github.com/conda-forge/miniforge) is a new
community-led installer that uses conda-forge as the default
channel, rather than defaults. This gives us a few advantages:
- No mixing of defaults & conda-forge channel by default. My
intuition is that this will reduce image size & build times,
but I don't know enough about conda to say if this is real
- It provides installers for architectures unsupported by miniconda.
This is particularly useful important for ARM & PowerPC, when we
want to support those better.
- I like conda-forge, and we should do what we can to support them!
This is a fairly easy, drop-in way to do so
- It is more likely to have newer versions of conda by default
than miniconda
- It provides sha256 hashes for installers rather than just md5. This
makes …
> Use miniforge instead of miniconda to get conda

- repo2docker/utils.py
- tests/unit/test_r.py
- tests/unit/test_utils.py
https://github.com/agladstein/stdpopsim/blob/binder/environment.yml#L20 uses a complex argument that our parsing of lines didn't handle. 
This PR makes our heuristic a bit smarter, but there are probably still cases we don't handle. I'd propose punting on them until we encounter them in the wild.
@agladstein this should fix the bug your reported in gitter earlier.
> [MRG] Fix long form args requirements

- repo2docker/buildpacks/_r_base.py
Both haven't been updated in a long time (~1yr) so we should refresh
them. This brings both to the latest commit in their repos.
Can anyone remember if there were big changes in either that would break things for users of repo2docker?
> [MRG] Update server proxy and rsession proxy

- docs/source/faq.rst
Thanks for this great project! I noticed two minor grammatical issues [in the FAQs](https://repo2docker.readthedocs.io/en/latest/faq.html#why-is-my-repository-is-failing-to-build-with-resolvepackagenotfound) today, and in this PR I propose fixes for them.
Thanks for your time and consideration.
> [docs] fix grammatical error in section title

- repo2docker/buildpacks/julia/julia_project.py
This works around a bug in Julia. I expect that this will be fixed eventually, and at that point we can put this extra call behind a version check.
> Work around a Julia bug

- repo2docker/buildpacks/conda/install-miniforge.bash
Use the latest released version of jupyter-offlinenotebook instead of a commit SHA1.
Related to https://github.com/jupyter/repo2docker/issues/724#issuecomment-616094914
> [MRG] pypi jupyter-offlinenotebook==0.1.0

- repo2docker/__main__.py
- repo2docker/app.py
- tests/unit/test_env.py
The goal here is make `repo2docker` process the `--env` option with the same semantics as the `--env` option to `docker` itself.
Closes #871
> [MRG] Change --env option to work like docker's

- tests/unit/test_env.py
This works around an issue where the temp directory can not be added to
Docker. In this case, the directory is immediately deleted, and does not
occupy significant disk space. There should be no impact to the move.
Fixes #881
> [MRG] Workaround Docker issue impacting some tests on macOS

- repo2docker/buildpacks/_r_base.py
The Shiny proxy was split out of the rstudio proxy package. This meant
that RStudio sessions were still being proxied but Shiny sessions not.
This was found by a user and reported in https://discourse.jupyter.org/t/shiny-applications-getting-redirect-errors/4340
> [MRG] Fix RShiny proxy

- repo2docker/buildpacks/_r_base.py
This bumps irkernel to v1.1. With this change https://github.com/betatim/r-conda/tree/betatim-patch-1 builds. Without it conda seems to sit and spin "solving the environment" in different modes for a long time/until after I ran out of patience.
I think bumping the version of irkernel should be harmless/not break things for users who don't care about the version of irkernel.
> [MRG] Bump version of irkernel for R 4.0

- docs/source/contributing/tasks.md
Some tests will fail if the configuration of the developer's machine is not as expected. The failures have distinct message patterns, so add workarounds for each type.
Fixes #884
> [MRG] Document test failure workarounds

- repo2docker/buildpacks/repo2docker-entrypoint
Discussed in Issue #883 - Make binder/start script not need to be executable
Now repo2docker-entrypoint ensures 'chmod u+x' is applied to the start script specified in $R2D_ENTRYPOINT.
This helps if the chmod applied in the build process doesn't affect the final executed copy of the start script file. For example, if the repo2docker is run as a 'local folder' source which is then mounted at /home/jovyan. The image's copy of the start script had +x set, but not in the local folder itself.
It will also fix start script problems with any repo source within my [ContainDS Desktop](https://containds.com/desktop) 'local binder' software.
> [MRG] chmod start script from repo2docker-entrypoint

- Dockerfile
I'm trying to add Docker into the Docker image so that I can run docker-in-docker with repo2docker which will facilitate GitHub Actions I am building at GitHub
I want to use repo2docker to power [codespaces](https://github.com/features/codespaces/) and this unblocks that for me.  I would rather depend on the official Jupyter image rather than maintaining our own.  Having this dependency will also unblock other future features. 
cc: @betatim @willingc
> Update Dockerfile to add Docker

- repo2docker/buildpacks/julia/julia_project.py
Julia 1.4.2 was released today, so this adds support.
> Add Julia 1.4.2 support

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.py-3.8.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.8.yml
- repo2docker/buildpacks/conda/environment.yml
Adds `nbresuse==0.3.3`, followed by [running `freeze.py`](https://github.com/jupyter/repo2docker/blob/master/docs/source/contributing/tasks.md#update-and-freeze-buildpack-dependencies)
JupyterLab automatically displays the metrics provided by nbresuse, it doesn't need a separate extension. Note that as mentioned in https://github.com/jupyterhub/binderhub/issues/1097#issuecomment-626628598 there are alternative JupyterLab front-ends for nbresuse, for instance https://github.com/jtpio/jupyterlab-system-monitor
Closes https://github.com/jupyterhub/binderhub/issues/1097
Screenshots from testing locally with `docker run -e MEM_LIMIT=200000000 ...`
Notebook:
Lab:
> [MRG] Add nbresuse==0.3.3 (full freeze.py)

- Pipfile
- dev-requirements.txt
- tests/unit/test_memlimit.py
Instead of checking that a build which allocates too much memory does
fail, we now only check that we pass the correct arguments to the Docker
API client. It seems reasonable to rely on the docker client working and
doing the right thing. This solves a problem where our CI is flakey
because the kernel of the VM the tests run on doesn't support this.
Hopefully this will make our CI faster and less flakey.
> [MRG] Make the memory limit test simpler

- repo2docker/buildpacks/nix/install-nix.bash
- This addresses issue #911
- This is untested, but there is no documented reason why repo2docker
should stick with the previously pinned version 2.1.1
- Upstream has switched from bz2 to xz, so `tar` now takes the `-J` flag
instead of `-j`
> Bump nix version to 2.3

- repo2docker/__main__.py
- tests/unit/test_argumentvalidation.py
In https://discourse.jupyter.org/t/how-to-build-mybinder-image-automatically-at-each-commit/5381 I noticed:
- the error message doesn't mention only lower-case letters are allowed for the Docker image name
- the formatting was incorrect, lines were concatenated without a space
> validate_image_name: mention lowercase, fix formatting

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.py-3.8.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.8.yml
- repo2docker/buildpacks/conda/environment.yml
I couldn't see any blockers in https://github.com/jupyter/repo2docker/issues/724 to upgrading to JupyterLab 2.0. I've started running into new extensions only work with jupyterlab 2 so I thought I'd open this to restart the discussion.
Closes https://github.com/jupyter/repo2docker/issues/724
> Update JupyterLab to 2.2.0

- repo2docker/buildpacks/conda/__init__.py
abcs should be imported from collections.abc, not collections itself, which is deprecated since 3.3, due to be removed in 3.9.
> avoid deprecated import of collections.abc

- repo2docker/buildpacks/julia/julia_project.py
Julia 1.5.0 just released yesterday. Hopefully this works for Binder.
> Add Julia 1.5.0 support

- repo2docker/buildpacks/conda/__init__.py
Currently, we can't open RStudio from the JupyterLab launcher because of the `x-frame-options: DENY` header that RStudio sends by default:
Opening `/rstudio` in its own tab works.
This PR adds the `www-frame-origin=same` config to `/etc/rstudio/rserver.conf`, [setting the header](https://docs.rstudio.com/ide/server-pro/access-and-security.html#frame-origin) to `X-Frame-Options: SAMEORIGIN`, allowing RStudio to be opened in the JupyterLab interface.
I'm making this PR since the config file is only writable as root and can't be fixed in `postBuild`. Let me know if I need to do anything further.
> Add `www-frame-origin=same` to /etc/rstudio/rserver.conf

- repo2docker/utils.py
- tests/unit/test_utils.py
This is a global flag which our inspection of `requirements.txt` files
should ignore as it doesn't imply a local reference.
> [MRG] Handle requirements.txt with `--pre` lines

- tests/unit/test_binder_dir.py
- merges 2 similar test cases
- replaces `in` with `==`, because `"binder" in ".binder"` returns True but it should return false in this test case
> little improvement for testing binder_dir

- repo2docker/buildpacks/julia/julia_project.py
Julia 1.5.1 was released last week.
> Add Julia 1.5.1 support

- .github/workflows/test.yml
- README.md
- docs/source/install.rst
- setup.py
This increases the lowest version of Python required to run repo2docker itself.
From https://www.python.org/dev/peps/pep-0478/ it looks like there will be no more new relases for 3.5 which is the first step towards it becoming unsupported.
Does someone remember why we should continue to support 3.5 for running repo2docker itself?
For #950 to land we need to have at least Python 3.6.
> [MRG] Bump Python requirement to 3.6 from 3.5

- docs/source/configuration/index.rst
- docs/source/usage.rst
[`Configuring your repository`](https://repo2docker.readthedocs.io/en/latest/configuration/index.html) is one of the main headings, so I think it should mention where configuration files should go.
> [MRG] Crosslink 'Configuring your repository' with usage

- .github/workflows/docker.yml
The Docker Cloud CI logs are currently inaccessible to the public
https://github.com/jupyterhub/repo2docker/pull/950#issuecomment-688731046
Regardless it's probably easier to have all CI workflows in one place.
> MRG: Add workflow to build Docker image

- .pre-commit-config.yaml
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/julia/julia_project.py
- repo2docker/buildpacks/julia/julia_require.py
- repo2docker/buildpacks/nix/__init__.py
- repo2docker/buildpacks/pipfile/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/contentproviders/dataverse.py
- repo2docker/contentproviders/figshare.py
The required Python version is now 3.6 (https://github.com/jupyterhub/repo2docker/pull/951).
`--target-version=py36` will allow in particular f-strings.
> Bump Black version to 20.8b1 and use --target-version=py36

- repo2docker/buildpacks/conda/install-miniforge.bash
See https://github.com/jupyterhub/mybinder.org-deploy/issues/1607
`${NB_PYTHON_PREFIX}/bin/jupyter labextension install jupyter-offlinenotebook || true` sometimes fails. This _may_ be due to excessive memory usage by the default build minimize step:
- https://discourse.jupyter.org/t/tip-binder-jupyterlab-extension/6022
- https://discourse.jupyter.org/t/jupyter-lab-build-hangs-and-then-fails-at-webpack-config-webpack-prod-minimize-config-js/6017/3
This PR disables the minimize step.
> MRG: Disable jupyterlab extension build minimize

- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/conda/install-miniforge.bash
cc @minrk - all tests are passing!
This is an update on #919 (I could not push to your branch anymore).
- The failure in #919 was due to a missing `-y` in `mamba install`, which caused the logs to overflow with repeted `Confirm changes: [Y/n]`
- I don't know why the `-y` was not required for the `conda install` command.
I also updated mamba to the latest
> Mamba number three

- repo2docker/buildpacks/conda/__init__.py
https://github.com/jupyterhub/repo2docker/pull/962 added some shell `time` statements for analysing performance.
One of the many hidden features of bash is the ability to [customise the format of the displayed time](https://datacadamia.com/lang/bash/time). This PR changes it to show only the realtime in seconds:
```
...
Successfully installed jupyter-offlinenotebook-0.1.0
time: 2.548
+ /srv/conda/envs/notebook/bin/jupyter labextension install --no-build jupyter-offlinenotebook
time: 4.406
+ /srv/conda/envs/notebook/bin/jupyter lab build --minimize=False
[LabBuildApp] JupyterLab 2.2.0
[LabBuildApp] Building in /srv/conda/envs/notebook/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod)
time: 93.153
...
time: 0.936
...
time: 233.246
Removing intermediate container …
```
> MRG: set TIMEFORMAT for timed bash conda commands

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/docker.py
Hi folks, thanks for repo2docker! :heart: 
In the generated Dockerfile, this combines a number of `COPY` and subsequent `USER` and `RUN chown` calls with the [`COPY --chown` syntax](https://docs.docker.com/engine/reference/builder/#copy).
Anecdotally, this seems to reduce the layer count a good deal: 45 vs 53 for one of the first tests that runs with just an `environment.yml`... my tests are still chugging, so I don't have a bunch of other data points, bless CI!
I haven't assessed the impact to size, but I would image it would result in a 2-1 reduction, as the `chown`ed files are, to my knowledge, copied in the subsequent layer. Can't hurt to look!
closes #164 
closes #861
> add chown to COPY commands to reduce layer count

- repo2docker/buildpacks/base.py
- tests/conda/repo-path/verify
It is my take to fix #974 by making sure `REPO_DIR` owned by `NB_USER`. It was recently changed by #969 leaving `REPO_DIR` owned by root when `REPO_DIR` was set to a directory other than `$HOME` by using `--target-repo-dir` option.
closes #974
> [MRG] Ensure REPO_DIR owned by NB_USER

- repo2docker/__main__.py
- repo2docker/contentproviders/git.py
Make repo2docker ready for the new default branch name on GitHub: `main`.
This already worked before and still works (bokeh renamed their default branch from `master` to `main` a while back):
```
$ repo2docker --no-build https://github.com/bokeh/bokeh-notebooks/
$ repo2docker --no-build --ref master https://github.com/bokeh/bokeh-notebooks/
```
A newly created repository that uses main as default branch name works:
```
repo2docker --no-build https://github.com/betatim/new-default-branch-name
repo2docker --no-build --ref master https://github.com/betatim/new-default-branch-name
```
This PR only changes an error messages and a help text. I couldn't find any other explicit references to `master` as default branch name.
closes #971
> [MRG] Remove reference to `master` branch from CLI doc

- repo2docker/buildpacks/base.py
- tests/base/node/README.md
- tests/base/node/verify
- tests/base/node10/README.md
According to the Releases page, node 10 will soon be out of maintenance:
https://nodejs.org/en/about/releases/
This change bumps the node version to 14.
Also for extra context: starting from https://github.com/jupyterlab/jupyterlab/pull/9282, JupyterLab requires node>=12, which currently makes the Binder preview builds fail: https://github.com/jupyterlab/jupyterlab/pull/9296#issuecomment-723226359
> [MRG] Update to node 14

- repo2docker/buildpacks/conda/install-miniforge.bash
- tests/conda/binder-dir/verify
Using mambaforge instead of miniforge, and saving some time by removing the call to `conda install mamba`.
> Use mambaforge instead of miniforge

- .github/workflows/test.yml
Test failures in PRs can sometimes be quite hard to debug. By adding a weekly automated test run of the default branch we'll have a bit more information on whether a PR is failing due to a change in that PR or due to some external factor. I've chosen Sunday, the time `10:36` was picked using `$RANDOM`.
> [MRG] Weekly test of master to check for external failures

- repo2docker/buildpacks/nix/__init__.py
- tests/nix/test-building/README.rst
- tests/nix/test-building/default.nix
- tests/nix/test-building/verify
The version bump #915 broke the Nix buildpack in case one does a build.
Nix 2.3 enables sandboxing by default. Building inside a Docker
container, while Nix is having sandboxing enabled is not possible. Thus,
sandbox = false should be set in /etc/nix/nix.conf.
cc @costrouc
> buildpacks/nix: disable sandboxing (bugfix)

- dev-requirements.txt
- repo2docker/contentproviders/dataverse.py
- repo2docker/contentproviders/doi.py
- repo2docker/contentproviders/figshare.py
- repo2docker/contentproviders/hydroshare.py
- repo2docker/contentproviders/zenodo.py
- setup.py
- tests/unit/contentproviders/test_dataverse.py
- tests/unit/contentproviders/test_doi.py
- tests/unit/contentproviders/test_figshare.py
- tests/unit/contentproviders/test_hydroshare.py
- tests/unit/contentproviders/test_zenodo.py
requests is globally simpler to use, and more and more people
are more familiar with this later than urllib.
See #988 for a discussion on why this is needed.
> Replace urllib by requests in contentproviders

- repo2docker/contentproviders/figshare.py
- tests/unit/contentproviders/test_figshare.py
See #999, let's keep that open until this is fully fixed
- The first commit copies @betatim's fix from https://github.com/jupyterhub/binderhub/pull/1236
- The second commit changes this fix to only check for an optional `code/` instead of any path element, this was needed to fix the `test_content_id` test where the returned mock URL is of the form `https://figshare.com/articles/title/9782777` which doesn't correctly match the regex from the first commit. I don't know if this is still correct though, I made this change to fix the test rather than from any knowledge of the Figshare API.
- The third commit highlights two tests which are still failing, I think this is a bug on the Figshare side? It looks like the version is dropped from the final redirect.
> MRG: Fix figshare test

- .codecov.yml
- .coveragerc
- .github/workflows/test.yml
(New comment from January 2020: https://github.com/jupyterhub/repo2docker/pull/982#issuecomment-765900791 if you like to skip ahead read that, for a historical perspective keep reading here.)
---
For some reason we report zero coverage from our tests.
For example here https://github.com/jupyterhub/repo2docker/runs/1297097310
All the files in `repo2docker/...` appear to have zero coverage and the file in `/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/repo2docker/...` do have some coverage. However when you look at what arrives in codecov you are at zero percent https://codecov.io/github/jupyterhub/repo2docker/commit/30ef2209cc767826e2647886854fac12469a06c1
> [MRG] Experiment with different install mechanism to get code coverage stats again

- docs/source/usage.rst
- repo2docker/app.py
- repo2docker/contentproviders/__init__.py
- repo2docker/contentproviders/swhid.py
- setup.py
- tests/unit/contentproviders/test_swhid.py
Add support for the SWHID content provider
This content provider allows to retrieve the content from a
Software Heritage (SWH) persistent identifier (SWHID).
Typical usage:
repo2docker swh:1:rev:94dca98c006b80309704c717b5d83dff3c1fa3a0
It uses the SWH public vault API to retrieve the content of the given
directory.
Most of the times, this will not need an authentication
token to bypass the rate-limiting of the SWH API.
Without authentication, one should be allowed to retrieve one
directory content per minute.
If this is not enought, then the user must use authenticated calls to
the SWH API.
For this, a new `swh_token` config item has been added to the Repo2Docker
application class.
To use authentication:
repo2docker --config cfg.json swh:1:rev:94dca98c006b80309704c717b5d83dff3c1fa3a0
with …
> Add a contentprovider for Software Heritage persistent ID (SWHID)

- repo2docker/buildpacks/repo2docker-entrypoint
- tests/unit/test_env.py
By streaming the logs also to a file users can access them from inside
the container which helps them debug issues without having to ask an
admin.
Follow up from https://github.com/jupyterhub/binderhub/issues/1156#issuecomment-703448118
> [MRG] Stream jupyter server logs to a file

- repo2docker/contentproviders/dataverse.py
- tests/unit/contentproviders/test_dataverse.py
A regression was introduced in https://github.com/jupyterhub/repo2docker/pull/993 which broke the Dataverse build process.
This should fix https://github.com/jupyterhub/binderhub/issues/1263 (the repo builds locally now).
also should there be a test for this?
> fix dataverse regression introduced in last release

- .circleci/config.yml
Should get that back to passing
SHouldn't these be redundant with readthedocs tests? I see we have rtd PR tests enabled, but I haven't seen CI results from rtd in a while. I'm not sure how to debug that
> bump python in circleci  test

- repo2docker/app.py
- repo2docker/buildpacks/repo2docker-entrypoint
- tests/unit/test_env.py
This is a follow up to #987 
As we observed there the `test_env.py` tests break. Locally this also happens, but only sometimes. After about half a day of messing around and trying to figure out where the logs go I am resigning myself to not being able to figure it out :-/
It seems even with somewhat "extreme" measures like in the PR you either get the logs from the command executed (both in the "normal" logs and the newly added "late logs" or you don't get them in either).
A thing that seems to help is to add a `; sleep 1` to the command the test runs.
This makes me think that the issue is related to buffering of some kind, some where. I am tempted to suggest we add the `sleep` to the test and assume that the flakeyness is due to the very short execution time of the container, which isn't …
> Investigating the missing logs

- repo2docker/buildpacks/r.py
Another patch to improve working behind a proxy.
This time the problem is, that gpg does not always respect the *_proxy env vars.
> buildpacks.r: dont use apt-key directly to respect *_proxy env vars

- repo2docker/buildpacks/conda/environment.frozen.yml
- repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.6.yml
- repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.7.yml
- repo2docker/buildpacks/conda/environment.py-3.8.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.8.yml
- repo2docker/buildpacks/conda/environment.py-3.9.frozen.yml
- repo2docker/buildpacks/conda/environment.py-3.9.yml
- repo2docker/buildpacks/conda/environment.yml
- repo2docker/buildpacks/conda/freeze.py
- use mamba to install in freeze.py to save time
- add 3.9 to frozen environment list
- bump notebook, nbconvert, jupyterhub-singleuser to current
> freeze with mamba, add 3.9

- repo2docker/buildpacks/julia/julia_project.py
- repo2docker/buildpacks/julia/semver.py
Instead of adding hard-coded version strings whenever a new release comes out, this PR fetches a list of currently available Julia versions from officially hosted [JSON](https://julialang-s3.julialang.org/bin/versions.json) file (JuliaLang/www.julialang.org#1101).
1. The resulting list `all_julias` should cover the same range we used to have, except it now contains more versions starting from 0.1.2, not 0.7.0 as we have now. I don't think this would cause a problem though as any projects relying on old 0.x versions would use REQUIRE file covered by julia_require.py.
2. Setting `default_julia_version` from `all_julias` is pushed back to the end of `julia_version` property to minimize json requests.
3. I noticed that our `find_semver_match()` is currently not fully compatible with [Pkg.jl …
> [MRG] Fetch available Julia versions from hosted json

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/python3-login
- repo2docker/buildpacks/repo2docker-entrypoint
- tests/unit/test_env.py
Per @manics idea, this reimplements the entrypoint in Python, mainly so we can better apply our expertise and understanding to it.
- repo2docker-entrypoint is now in Python
- shebang points to new `python3-login` to preserve login-shell behavior (source profiles, etc.) because we can't nest interpreters in a single shebang line. First attempt extracted login env from a subprocess, but I think this is a little more natural, maybe, as it matches the usual process hierarchy (bash -l > Python > 'real' entrypoint.
- make sure PYTHONUNBUFFERED env is set, which is ~always needed in containers
- tee is implemented in Python with nonblocking
- all available signals except a select few that cannot be caught (SIGKILL, SIGSTOP) and shouldn't (SIGCHLD) are relayed to the child
It seems to work! …
> reimplement entrypoint in Python

- README.md
For some reason the URL we use to get the logo has stopped working. This updates the URL to a recent commit.
Out of curiosity it would be cool to understand why this broke.
> Fix logo URL in README

- repo2docker/buildpacks/julia/julia_project.py
[Julia 1.6](https://julialang.org/blog/2021/03/julia-1.6-highlights/) just released.
> Set default Julia version to 1.6

- .github/workflows/test.yml
- repo2docker/contentproviders/hydroshare.py
- tests/unit/contentproviders/test_hydroshare.py
The build process was broken by https://github.com/jupyterhub/repo2docker/pull/993, binderhub wasn't able to build hydroshare repos.
> Fix regression in hydroshare introduced after moving to requests

- Dockerfile
ruamel.yaml depends on ruamel.yaml.clib, which requires
compilation on alpine. It did not seem to require the
packages in build-base before, but it does now.
> Add build-base to build stage of docker image

- docs/source/conf.py
add_stylesheet has been deprecated for a while.
This should hopefully fix the CI failures in circleci
> Stop using deprecated add_stylesheet in sphinx

- docs/doc-requirements.txt
Follow-up to https://github.com/jupyterhub/repo2docker/pull/1050
This pins the versions of all doc dependencies, so we can rely on dependabot to check for problems with updates.
There's no dependabot.yml file in https://github.com/jupyterhub/repo2docker/tree/master/.github but it looks like dependabot has previously opened PRs in this repo: https://github.com/jupyterhub/repo2docker/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed
so presumably it's been configured elsewhere?
> Pin doc requirements to avoid CI breakages

- repo2docker/app.py
- repo2docker/docker.py
- repo2docker/engine.py
- setup.py
Shouldn't change much, but a refinement of #1008
- use `since` when fetching late logs to reduce duplicated output (does not eliminate it due to required integer-second rounding of timestamps; requires UTC timestamp parsing not in the Python stdlib. :sigh:)
- demote late logs to debug-level, since they may not include any new output at all, and always include redundant output
- use capfd to capture output in test_env for easier debugging
> Refine buffered output debugging

- setup.py
The `setup.py` file is missing the imported dependency [chardet](https://pypi.org/project/chardet/). This PR adds that dependency 
PR will fix issue #1063
> fix: add chardet, a not explicitly declared dependency

- Dockerfile
- setup.py
`repo2docker` depends on `docker`, but `docker==5.0.0` is failing to import its dependency `six` and isn't getting patched because of a lack of maintainers it seems.
This is a PR similar to one we have done for `chartpress` as well (https://github.com/jupyterhub/chartpress/commit/8b486732f4ea518f65f4538dbb4e334f5e8aa5c6). The reason for repo2docker tests succeeds anyhow without this workaround is because six is available due to other reasons in the environment where tests run apparently.
PS: The Dockerfile was updated as installing a six wheel would fail as it would uninstall an existing six first but run into a failure doing so, so I adjusted the Dockerfile to not try to install a `six` wheel from the previous Dockerfile build step.
Closes #1039
> Workaround docker-py dependency's failure to import six

- README.md
- docs/source/conf.py
- docs/source/config_files.rst
- docs/source/contributing/buildpack.md
- docs/source/contributing/contentprovider.rst
- docs/source/contributing/contributing.md
- docs/source/contributing/roadmap.md
- docs/source/contributing/tasks.md
- docs/source/faq.rst
- docs/source/howto/user_interface.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/usage.rst
- hooks/post_push
Following process from https://github.com/jupyterhub/team-compass/issues/412
```
.github/workflows/release.yml:        uses: pypa/gh-action-pypi-publish@master
```
External action
```
docs/source/conf.py:# The master toctree document.
docs/source/conf.py:master_doc = "index"
docs/source/conf.py:        master_doc,
docs/source/conf.py:man_pages = [(master_doc, "repo2docker", "repo2docker Documentation", [author], 1)]
docs/source/conf.py:        master_doc,
```
Sphinx stuff
```
repo2docker/_version.py:        # "stabilization", as well as "HEAD" and "master".
```
Versioneer stuff
```
repo2docker/contentproviders/git.py:                if ref == "master":
repo2docker/contentproviders/git.py:                        "Failed to check out the 'master' branch. " …
```
> Rename master branch to main

- .github/workflows/release.yml
- Dockerfile
- README.md
- hooks/README.md
- hooks/post_push
The `jupyter/repo2docker` Docker Hub image [hasn't been updated for 20 days (last tag is 16 July 2021)](https://hub.docker.com/r/jupyter/repo2docker/tags?page=1&ordering=last_updated).
[Two PRs have been merged](https://github.com/jupyterhub/repo2docker/pulls?q=is%3Apr+merged%3A%3E2021-07-16+) since that last build and those should've triggered a new Docker image.
Automated Docker Hub builds were meant to be [discontinued from 18 June](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) which is before the last build, but perhaps they kept going for a bit longer?
This PR is a copy of https://github.com/jupyterhub/repo2docker/pull/1055 but for amd64 only.
Since this is building for the native architecture there should be no time penalty in using docker buildx.
Required:
> GitHub workflow build and push to Docker hub

- Dockerfile
The Docker build has broken (again): https://github.com/jupyterhub/repo2docker/runs/3506339228
```
#12 25.59 rm: can't remove '/tmp/wheelhouse/six*.whl': No such file or directory
#12 ERROR: executor failed running [/bin/sh -c mkdir /tmp/wheelhouse  && cd /tmp/wheelhouse  && pip3 install wheel  && pip3 wheel --no-cache-dir /tmp/src  && rm /tmp/wheelhouse/six*.whl  && ls -l /tmp/wheelhouse]: exit code: 1
```
This reverts commit https://github.com/jupyterhub/repo2docker/pull/1066/commits/f3906be35b9af1c1fef70864c90c76bcfe4d8004 from https://github.com/jupyterhub/repo2docker/pull/1066
> Fix Docker build (again)

- docs/source/howto/user_interface.rst
reverse docs since now classic notebook is opt-in and lab is default, instead of vice versa. Everything else is the same.
> update user_interface doc to reflect that lab is default

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/buildpacks/docker.py
- repo2docker/docker.py
- repo2docker/engine.py
We'd like to build our own custom images based on our own Docker Base-Images.
It works mostly fine, but the one big issue I ran into is that our Jupyter Hub does not show the images in its UI after successfully building them.
This is due to the labels it set on the command line not actually making it into the image. Adding them is easily achieved by adding this single line.
I also noticed that tljh makes use of an appendix to set some more stuff. So I extended this PR to have support for it as well.
For appendices to work, I needed to modify the Dockerfile on the fly, so I added that to the render method of the Docker BuildPack.
While making the build method based on that, I eventually realized that I had effectively re-implemented the base classes build method, with next to no …
> Set labels when building image from Dockerfile

- repo2docker/buildpacks/_r_base.py
- repo2docker/buildpacks/r.py
We redirect stdout (not stderr) of apt-get update and install
in most other places (check out base.py) to not clutter the
output
> Quieter R builds

- repo2docker/__main__.py
- repo2docker/app.py
This is effectively the second part of https://github.com/jupyterhub/repo2docker/pull/1097
Instead of allowing an appendix for custom Dockerfiles, this adds the ability to pass arbitrary build args to the build process, which is much cleaner and more predictable than appending lines to the Dockerfile.
For the normal buildpacks this does generally nothing, since they don't expect any buildargs you can't already set via other switches, but for custom Dockerfiles it adds a range of new possibilities.
> Add command line option to pass extra build args

- repo2docker/buildpacks/conda/freeze.py
I usually run `python freeze.py --help` to remind myself of how it works..... but instead it creates a `environment.py---help.yml` file
> Add help message to freeze.py

- repo2docker/buildpacks/r.py
- tests/r/simple/verify
- tests/unit/test_r.py
3.6 is almost 4 years old now.
Related to https://github.com/jupyterhub/repo2docker/pull/1104 which
brings in a lot of other R improvements.
> Bump default R version to 4.1

- repo2docker/buildpacks/r.py
- tests/unit/test_r.py
PPA is a specific kind of apt repository, hosted on
launchpad.net. We use https://cran.r-project.org/bin/linux/ubuntu/,
which is just a regular apt repository. The PPA terminology
always confused me, so this just clears that up
> Say 'apt repository' rather than PPA

- repo2docker/buildpacks/_r_base.py
- repo2docker/buildpacks/r.py
- tests/unit/test_r.py
r-recommended is a collection of common CRAN packages, which cause conflicts when trying to install older R because "Ubuntu packages for R" only support installing packages with the "latest stable R", not pinning older versions, and apt doesn't seem to have a real solver. This should be okay for us, as long as we only get R itself from apt, and not any of the CRAN packages, which can be retrieved from a regular CRAN install.
The reason I think this will be relatively safe, despite "Ubuntu for R" packages not supporting old builds of R is that `r-base-core` and `r-base-dev` do not have any dependencies on any other packages from the Ubuntu for R repo - all of their dependencies are from Ubuntu itself (Check the output of `apt-get install`). The "only latest stable" issue and conflicts we …
> Only get R itself (r-base-core) from apt, not CRAN packages

- tests/conda/r3.6/environment.yml
- tests/conda/r3.6/verify
- tests/r/mran/install.R
- tests/r/mran/verify
- tests/r/r3.6/install.R
- tests/r/r3.6/verify
- tests/r/r4.0-rspm/install.R
- tests/r/r4.0-rspm/verify
- tests/r/r4.0/install.R
- tests/r/r4.0/verify
- tests/r/r4.1/install.R
- tests/r/r4.1/verify
- tests/r/simple/install.R
- tests/r/simple/verify
ggplot2 is a big library with a bunch of dependencies,
making our already slow R tests even slower. This PR
switches them to using the tinytest library, which has
no dependencies and is much smaller.
> Use a smaller R library in our tests

- repo2docker/buildpacks/r.py
This can often leave ~100-200MB in /tmp that isn't re-used
after the image is set up.
> Delete /tmp/downloaded_packages after running install.R

- repo2docker/buildpacks/_r_base.py
- repo2docker/buildpacks/julia/julia_project.py
- repo2docker/buildpacks/julia/julia_require.py
- repo2docker/buildpacks/r.py
- repo2docker/semver.py
- tests/unit/contentproviders/test_mercurial.py
- tests/unit/test_semver.py
Python is removing all version-string parsing from the standard library, so use the semver utilities we already have for Julia.
Had to add some zero-padding, because `semver.VersionInfo.parse` is unnecessarily pedantic and doesn't accept '1' or '1.0', only '1.0.0'.
> Remove deprecated calls to distutils

- repo2docker/docker.py
Puts it in the ContainerEngine interface specific to Docker,
so PodMan can implement its own when necessary.
Fixes https://github.com/jupyterhub/repo2docker/issues/711
> Allow passing in extra args to Docker initialization

- repo2docker/__main__.py
- repo2docker/app.py
Without this, you *always* needed a repo2docker_config.py
file to configure anything. This PR makes r2d match the
behavior of most traitlets based applications (like jupyter_server,
jupyterhub, nbconvert, etc)
Fixes https://github.com/jupyterhub/repo2docker/issues/1112
> Allow passing in traitlets via commandline

- Dockerfile
In order to use podman as a backend for repo2docker (a la https://github.com/manics/repo2podman),
a minimum version of Alpine 3.14 is needed.
> [MRG] Update Dockerfile to current Alpine (ALPINE_VERSION=3.15.0)

- repo2docker/app.py
> [MRG] Pass build_args to `render()` during `--no-build` for consistency with regular builds

- repo2docker/buildpacks/_r_base.py
- tests/conda/r-unspecified/environment.yml
- tests/conda/r-unspecified/verify
when getting r-base from conda, `self.r_version` may be a falsy empty string. We can't do version comparisons when we don't have a version to compare!
closes #1140
> handle r version being unspecified in environment.yml

- .pre-commit-config.yaml
- tests/unit/test_editable.py
Fixes error with click causing current CI failures
> Update black version

- docs/source/howto/languages.rst
- Explains https://github.com/jupyterhub/repo2docker/pull/1104
- Advertises that we get RStudio 'for free' when R is installed
> Update 'how to get R' section

- repo2docker/buildpacks/repo2docker-entrypoint
This PR addresses an issue in the docker entrypoint where the `REPO_DIR` in the container is owned by the `NB_USER`'s default UID and GID but the `-u` option to docker was specified to override the `NB_USER`'s UID and GID. Without this fix:
```
docker \
run \
-i \
-v \
--mount=type=bind,source=/tmp/t9ig2rxb,target=/kvyoQW \
--mount=type=bind,source=/tmp/tuafqr29,target=/tmp \
--workdir=/kvyoQW \
--user=4001:4001 \
--rm \
--cidfile=/tmp/vsiq7g3w/20220415125043-084473.cid \
--env=TMPDIR=/tmp \
--env=HOME=/kvyoQW \
pymonger/downsample-landsat:2.0.3 \
/bin/sh \
-c \
papermill /home/jovyan/downsample-landsat/stage_in.ipynb output_nb.ipynb --parameters input_url "https://github.com/pymonger/downsample-landsat/releases/download/1.0.0/LC08_L1TP_065045_20211205_20211215_02_T1_QA_PIXEL.TIF" …
```
> handle permission issue writing .jupyter-server-log.txt in REPO_DIR

- repo2docker/buildpacks/_r_base.py
There are 2 main changes:
- upgrade RStudio Server (v2022.02.1)
- use the same versions for RStudio Server and jupyter-rsession-proxy independent of R version
The changes are motivated by #1145 .
> [MRG] upgrade RStudio Server to v2022.02.1

- repo2docker/contentproviders/dataverse.json
NASA's Jet Propulsion Laboratory recently implemented a dataverse installation and would like to be able to use it with repo2docker / binderhub.
> Add JPL Dataverse

- .github/workflows/release.yml
In the settings for this project, there were two separate api tokens setup for this project. One stemming from `mybinderteam` account in PyPI, and one for `jupyterhub-bot`. Only the latter has 2FA enabled, so in this PR I'm switching to using that PyPI API token instead and have removed `mybinderteam` on PyPI to have access to this package.
- https://github.com/jupyterhub/repo2docker/settings/secrets/actions
- https://github.com/jupyterhub/team-compass/issues/539
> ci: switch to using a 2fa enabled accounts pypi api-token

- repo2docker/contentproviders/zenodo.py
- tests/unit/contentproviders/test_zenodo.py
Test uploads should go to the sandbox, rather than to
main zenodo. The installation is exactly the same.
> Support pulling from zenodo sandbox too

- repo2docker/buildpacks/conda/freeze.py
The latest conda-lock needs `--kind=explicit` to match the current expectations of `freeze.py` (originally written for conda-lock 0.8): https://github.com/conda-incubator/conda-lock#pre-10-compatible-usage-explicit-per-platform-locks
The Python 3.6 lockfile was removed in https://github.com/jupyterhub/repo2docker/pull/1149
> Freeze.py update

- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
Started as one fix, but now it's a couple:
- Avoid redundant resolution in Dockerfile pip install
avoids error attempting to 'upgrade' a package installed by apk (a dependency of mercurial, perhaps), which pip refuses.
Since dependencies are resolved already, adding `--ignore-installed --no-deps` just installs all the wheels as-is, skipping the redundant solve (already done in `pip wheel`) and upgrade.
- Update GHA runners to 20.04, since 18.04 is shutting down. This, in turn, changes how mercurial is installed to be a simple pip install, since `hg` is using Python 2.
> get CI working again

- repo2docker/docker.py
our base-env setup assumes amd64, so avoid platform issues on e.g. ARM macs. We should be explicit in telling the builder that it _must_ be amd64.
I believe this closes #1174 (it works for me, though I had to clean out image caches to resolve errors)
> explicitly build linux/amd64 images

- repo2docker/app.py
- repo2docker/buildpacks/conda/__init__.py
our logger was never being quite hooked up when not using JSON loggers, meaning that log messages (such as those fixed here to include newlines) were never shown.
> consistent log handling when not using JSON loggers

- Dockerfile
avoids extra layer of unused wheel files
use mounted pip cache instead of disabling cache - all the benefits of no cache (size), and all the benefits of cache (local rebuild time).
I think we should consider enabling cache mounts instead of `--no-cache-dir` in repo2docker builds themselves, but that means requiring buildkit, which affects users. Requiring buildkit in our own image doesn't affect users at all.
see also : https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2856
> mount wheels from build stage instead of copying them

- repo2docker/buildpacks/conda/__init__.py
- tests/unit/test_buildpack.py
rather than warning (which users usually won't notice) and building with the wrong version of Python
closes #1183 (also closes #552 which is the same)
I think this was originally a warning because at some point we had a second step to explicitly install the requested Python version _after_ setting up the base env, so it still _could_ work, but without a fully frozen env. Then that step could potentially fail informatively if e.g. the requested Python didn't exist. But we don't do that anymore (if we ever did, I don't trust my memory), so failing seems better than the current behavior of just using the default Python instead.
> fail on unsupported Python

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/contentproviders/git.py
- repo2docker/contentproviders/mercurial.py
- repo2docker/utils.py
Replace the phase strings used in logs with an Enum.
This is a follow-up to https://github.com/jupyterhub/binderhub/pull/1525#issuecomment-1222036439 and replaces the inconsistent use of `failed`/`failure` with `failed`
> Use enum to standardise `phase`

- .github/dependabot.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- dev-requirements.txt
Just passing by trying to keep this repo up to date with various practices across the JupyterHub organization, fixing details such as ensuring the use of a pip cache is robust.
This should not have any influence on the actual function of repo2docker, just the CI system.
> ci: general refresh of github workflows, update gha versions and let dependabot do it, etc.

- repo2docker/buildpacks/conda/__init__.py
If r-base is pinned, r-irkernel will resolve to a version that is compatible with it. But if we pin r-irkernel and not r-base, the opposite will happen and we will end up with an older version of r-base than is supported by r-irkernel's modern versions.
I find debugging how versions resolve with conda is really tricky, so unless we have clear principles of what the pin should be and why, I strongly advocate we don't have it pinned here.
In this case, having r-irkernel pinned to 1.2 caused us the conda buildpack to get stuck at R version 4.1 instead of going to R 4.2 that is now available. Using a runtime.txt without R pinned will result in 4.2 though, but the conda buildpack is stuck at 4.1 without this.
- A test to catch this is available in #1188. If this is merged, we can remove a …
> Remove conda buildpacks pin of r-irkernel to 1.2

- docs/source/changelog.rst
We're going to bump `jupyterhub-singleuser` to 3.0.0
https://github.com/jupyterhub/repo2docker/blob/d7be04efb590a2a1227614ccaf9b504ad9333470/repo2docker/buildpacks/conda/environment.yml#L11
https://github.com/jupyterhub/binderhub/pull/1544#issuecomment-1278971454
I think we should make a release before doing so.
Generated with
```
github-activity --target jupyterhub/repo2docker --since 2022.02.0  | sed -r \
-e 's%\[#([0-9]+)\]\(https://github.com/jupyterhub/repo2docker/pull/[0-9]+\)%:pr:`\1`%' \
-e 's%\(\[\@([A-Za-z0-9-]+)\]\(https://github.com/[A-Za-z0-9-]+\)\)%by :user:`\1`%'
```
I think
is the only open PR that's close to being merged. It's not required for this release though.
> Initial changelog for 2022.10.0

- tests/conftest.py
- tests/unit/contentproviders/test_git.py
avoids assertion with file-based submodules, without any changes to git config by using one of the safe submodule transports.
alternative to #1203 
benefit of #1203: fully local, doesn't rely on external repo (we have lots of tests that do, so I'm not sure this is a big benefit)
benefit of this one: doesn't rely on non-default git config, more realistic to actual submodule use
closes #1198
> run submodule test over https

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/utils.py
- tests/unit/test_args.py
- tests/unit/test_ports.py
Allows specifying `-p9999` or `-p5555:9999` without also needing to override the default command
app retrieves port arguments from length-1 port mapping for default command, instead of requiring random port OR overriding the whole command.
> allow user to specify a single port with default command

- repo2docker/buildpacks/base.py
- tests/conda/r3.6-target-repo-dir-flag/verify.py
- tests/conftest.py
- __Non-existing REPO_DIR folder__
If users provide a REPO_DIR as a build arg to a folder that doesn't exist, the root user will create it but leave the non-root user without permissions to access it. This PR resolves that and adds a test to verify it by adding some `mkdir` and `chown` statements.
- __Dockerfile refactoring__
It includes basic refactoring of the Dockerfile to reduce the layers by coalescing ENV statements and making use of the recommended syntax with explicit `=` in ENV statements.
- __Refined test documentation__
It updates a comment to clarify how the test suite works.
---
**Updated**
This PR (originally attempted to try out some alternatives to #974 and (#975) now:
- > changes the target dir TBD (might not, if #975 changes are sufficient: @manics and @tomyun offered …
> Allow REPO_DIR to be a non-existing folder by creating it and providing the user with permissions

- .github/workflows/release.yml
- .github/workflows/test.yml
- dev-requirements.txt
I understand it as using setup.py directly is being phased out in favor of using for example `build` that I think can handle building wheels for packages with `setup.py` or `pyproject.toml`.
> Create wheels with the build package, stop calling setup.py directly

- .github/workflows/test.yml
I've activate pre-commit.ci to run against this github repo already and it works. This PR updates the pre-commit job that also acted as a job populating a pip cache as just a job that populates the pip cache, and does so a bit more completely.
This PR includes #1199 that introduced the `build` package into dev-requirements.txt.
> ci: stop running pre-commit in gha, rely on pre-commit.ci

- repo2docker/buildpacks/pipfile/__init__.py
When `pipenv install` is run, it emits various cache files. Ideally, they would be cleaned up. In #1126 @minrk added the `--clear` flag to the `pipenv install` statement, but that didn't seem to work properly.
I made some code inspection and concluded it seems like `--clear` is bypassed when used with `pipenv install`. I consider this a bug in `pipenv`. I didn't find issues about it, and I didn't report it as I'm not certain if its fixed in their latest versions or not and wanted to focus on repo2docker maintenance now.
Closes #1207 and enables #1126 to not include a somewhat unrelated PR/commit.
This PR has been tested to have the desired effect in #1126.
> pipfile: pass --clear flag, and do it separetely to not be ignored

- repo2docker/buildpacks/_r_base.py
- repo2docker/buildpacks/pipfile/__init__.py
- tests/check-tmp
- tests/conftest.py
- tests/venv/postBuild/postBuild
This mostly lays the _infrastructure_ for #1121 
- re-use images and skip build stage in verify/check-tmp tests Should save some time, even though the build cache would have been used.  This way, we don't run through the build to check the layer cache.
- check-tmp checks disk usage in a collection of directories and fails if they exceed a certain size, reporting on their contents
What dirs should we check?
---
EDIT: closes #1207
> Add check-tmp step to local repo tests

- .github/workflows/test.yml
- dev-requirements.txt
The python based CLI `codecov` is deprecated, and is maybe what has caused intermittent but often occuring codecov issues recently. They now recommend use of a binary that is also available by using a github action as we will go ahead and do here.
> ci: use non-deprecated codecov uploader

- Dockerfile
The docker image builds are failing on main:
```
#15 4.364 Collecting hg-evolve
#15 4.412   Downloading hg-evolve-10.5.3.tar.gz (847 kB)
#15 4.445      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 847.1/847.1 kB 29.2 MB/s eta 0:00:00
#15 4.621   Preparing metadata (setup.py): started
#15 4.828   Preparing metadata (setup.py): finished with status 'error'
#15 4.835   error: subprocess-exited-with-error
#15 4.835   
#15 4.835   × python setup.py egg_info did not run successfully.
#15 4.835   │ exit code: 1
#15 4.835   ╰─> [1 lines of output]
#15 4.835       ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
#15 4.835       [end of output]
#15 4.835   
#15 4.835   note: This error originates from a subprocess, and is likely not a problem with pip.
#15 …
```
> Quick-fix for Docker image build

- repo2docker/buildpacks/conda/install-base-env.bash
- tests/conda/py35-binder-dir/verify
In this PR, I update mamba to version 1.1, and enable the rich conflict error messages.
For more information about the rich error messages, you can check out the following post:
https://medium.com/@AntoineProuvost/managing-conflicts-with-mamba-6a5fa10ed6a
Old conda error message:
New mamba 1.1 error message:
We have not seen any issue with this in the past few weeks and plan on removing the "experimental" flag very shortly.
> Upgrade to mamba 1.1 and enable rich SAT error messages

- .gitpod.yml
Gitpod is really convenient for updating packages and running `python freeze.py`. However one has to install the dev dependencies to be able to lock the environments.
This PR automatically installs the dev dependencies on Gitpod so the env is ready on startup.
This also follows the documentation for setting up a dev environment: https://repo2docker.readthedocs.io/en/latest/contributing/contributing.html#set-up-a-local-virtual-environment
> Also install dev requirements on Gitpod

- repo2docker/buildpacks/conda/__init__.py
Currently RStudio packages installed in the environment do not show up in RStudio. The current workaround is to set the `LD_LIBRARY_PATH` environment variable in the `start` file. This change applies a similar fix during the build, adding the proper library path to `rserver.conf`.
Relevant discussion can be found in #1153 and here:
https://discourse.jupyter.org/t/glibcxx-3-4-26-not-found-from-rstudio/7778/5
> Add Conda env library path to RStudio configuration

- docs/source/config_files.rst
- docs/source/faq.rst
covers #1219 and #1239 and a proposal for (the Python version part, at least) of #1220 . It's vague enough right now to encapsulate what we will probably do (more frequent smaller upgrades) without specifying a strict upgrade policy, yet.
> update docs for default and supported Python versions

- .codecov.yml
it's unreliable right now, and we don't want to waste time with incorrect failed status checks
the links in the checks are the main value, not the pass/fail. This matches how it's used in most other jupyterhub repos.
> disable codecov failures

- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/julia/julia_project.py
- repo2docker/buildpacks/julia/julia_require.py
- repo2docker/buildpacks/nix/__init__.py
- repo2docker/buildpacks/pipfile/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/r.py
ensures `get_` functions are called only once, avoiding duplicate log statements. Closes #1246 .
This may be too clever to do it magically on methods that start with `get_`, but it works and is the _simplest_ if we want to clearly always cache all these methods (I think we do).
The alternatives are:
1. more standard, far more changes (both now and over time) - apply `@lru_cache()` on every method, including every subclass method override (easy to miss, as the only downside of forgetting it is duplicate log statements and a negligible amount of wasted time)
2. to ensure these methods are called only once on the parent class, e.g. by assigning the results to variables, or calling directly via an additional private method `self._get_...`. This is ultimately the same as the memoize here, but …
> avoid duplicate log statements by memoizing getters

- repo2docker/contentproviders/dataverse.py
- tests/unit/contentproviders/test_dataverse.py
Dataverse creates plain-text, preservation-friendly copies of certain file formats (some of which are proprietary, such as Stata or SPSS) and this .tab (tab-separated) file is downloaded unless you supply `format=original`, which is what this pull request does.
The original filename (e.g. foo.dta, a Stata file) comes from `originalFileName`, which is only populated when the preservation copy (e.g. foo.tab) has been successfully created.
Additional variables were created to distinguish between `filename`, `original_filename`, and `filename_with_path`. If `original_filename` is available, it's the right one to use.
To allow the tests to continue passing, the query parameters are now removed so just the file id can be cast as an int.
I tested it with a random dataset that has Stata files …
> [MRG] download original file formats from Dataverse #1242

- repo2docker/buildpacks/julia/julia_project.py
we aren't showing the error, just `{e}`
> missing `f` in julia fetch error f-string

- docs/source/howto/languages.rst
- repo2docker/buildpacks/r.py
- tests/r/r4.0-rspm/verify
- tests/unit/test_r.py
Update location of Posit packagemanager per https://status.posit.co/
Fixes #1272
> Update the location of R packagemanager

- docs/source/conf.py
missing `%s` raises error on sphinx 6
closes #1275
> fix github link templates

- repo2docker/docker.py
- repo2docker/engine.py
- tests/unit/test_docker.py
This is to help with setting dynamic registry credentials when pushing in BinderHub
Example using traitlets on the command line:
`repo2docker --push --no-run --image-name docker.io/USERNAME/image:test --ContainerEngine.registry_credentials=registry=docker.io --ContainerEngine.registry_credentials=username=USERNAME --ContainerEngine.registry_credentials=password=PASSWORD https://github.com/binderhub-ci-repos/cached-minimal-dockerfile`
Example using environment variable:
`CONTAINER_ENGINE_REGISTRY_CREDENTIALS='{"registry":"docker.io","username":"USERNAME","password":"PASSWORD"}' repo2docker --push --no-run --image-name docker.io/USERNAME/image:test https://github.com/binderhub-ci-repos/cached-minimal-dockerfile`
> Add optional registry credentials to push()

- docs/source/howto/lab_workspaces.rst
This changes a link from an unmaintained repository to the official JupyterLab documentation.
> Point to official documentation for handling JupyterLab workspace

- repo2docker/buildpacks/_r_base.py
Fix https://github.com/jupyterhub/repo2docker/issues/1290. 
Note that `apt-cache search libssl3` returns the exit code 0 even if there is no match.
> Fix rstudio-build selection

- docs/source/design.md
- docs/source/howto/base_image.md
- repo2docker/app.py
- repo2docker/buildpacks/r.py
- tests/conftest.py
18.04 was EOL May 2023, with only paid support now available (https://ubuntu.com/blog/18-04-end-of-standard-support).
Let's bump the default base image to 22.04. This might break some repos that have apt.txt based packages, but I don't really think there's a way around that. If specific package pinning is needed, users unfortunately need to use a Dockerfile.
Closes #1258
> Upgrade base image from to Ubuntu 22.04 from 18.04

- docs/source/config_files.rst
- docs/source/howto/breaking_changes.md
- docs/source/howto/index.rst
Merging https://github.com/jupyterhub/mybinder.org-deploy/pull/2742 is a breaking change, so we need some user-facing documentation
Closes https://github.com/jupyterhub/repo2docker/issues/1304
We could also think about our long term strategy for `apt.txt`. IIRC at least one comment in the distant past suggested deprecating it.
> Add Ubuntu 22.04 upgrade guide

- repo2docker/contentproviders/doi.py
- repo2docker/contentproviders/zenodo.py
- tests/unit/contentproviders/test_doi.py
- tests/unit/contentproviders/test_zenodo.py
I've tried to get Zenodo working again by inspecting the API responses from
- https://zenodo.org/api/records/3242074
- https://zenodo.org/api/records/3242074/files 
Closes https://github.com/jupyterhub/repo2docker/issues/1314
> Get Zenodo working again

- repo2docker/buildpacks/r.py
This is useful for investigating RStudio problems, such as https://github.com/jupyterhub/repo2docker/issues/1316.
In future it'd be nice if we had an easy way to set the log level to `debug` for investigating problems, but for now you'll need to modify the R2D source code.
> rstudio: log-level info to stderr

- repo2docker/contentproviders/dataverse.json
We recently moved our Dataverse repository "Edmond" from https://edmond.mpdl.mpg.de to https://edmond.mpg.de.
Currently, we still have old DOIs registered with the old URL, new DOIs are registered with the new URL. There are of course redirects, but as the dataverse.py script directly compares the URL from the DOI with the list of dataverse installations, DOIs with the new URL do not work with MyBinder anymore.
This pull requests adds a second entry for "Edmond" with the new domain, so both types of URLs should work. This is just a temporary solution. We are planning  to migrate the old DOIs to the new domain. As soon as this process is finished, the entry for the old domain could be deleted (we will provide another pull request then).
In the meantime, we'd appreciate if you allow us two …
> New domain for Edmond MPG repository

- docs/source/howto/base_image.md
Some users(me) didn't know how to set `base_image`.
Add an example of how to set it.
I didn't konw **traitlet** meaning.
<hr>
This is the first time contribution to this project.
Please let me know if I violate the guidelines.
> [MRG] docs: Add base_image parameter example.

- dev-requirements.txt
- tests/conftest.py
pytest 8 breaks our tests:
```
ERROR tests/base/node - pytest.PytestRemovedIn8Warning: The (fspath: py.path.local) argument to LocalRepo is deprecated. Please use the (path: pathlib.Path) argument instead.
See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
```
Reported in https://github.com/jupyterhub/repo2docker/pull/1329#issuecomment-1913608729
> Support pytest=8

- repo2docker/buildpacks/conda/install-base-env.bash
- tests/conda/py35-binder-dir/verify
> Update mamba to 1.5.7 from 1.5.1, and conda to 24.3.0 from 23.7.4

- Dockerfile
Brings us to latest alpine, and to a newer python
> Dockerfile: bump alpine from 3.17 to 3.19 and Python 3.10 to 3.11

- docs/source/changelog.md
We're about to make some breaking changes including https://github.com/jupyterhub/repo2docker/pull/1340 so lets get a release out first.
> Changelog for 2024.03.0

- docs/source/usage.rst
- repo2docker/app.py
- repo2docker/contentproviders/__init__.py
- repo2docker/contentproviders/ckan.py
- tests/unit/contentproviders/test_ckan.py
This PR add support for [CKAN](https://ckan.org/) datasets as content provider for repo2docker, e.g.:
```
repo2docker https://demo.ckan.org/dataset/sample-dataset-1
```
It has been tested on some CKAN repositories such as:
- data.gov (https://catalog.data.gov/dataset/fdic-failed-bank-list)
- Canada Open Government Portal (https://open.canada.ca/data/en/dataset/d8f85d91-7dec-4fd1-8055-483b77225d8b)
- NHM Data Portal (https://data.nhm.ac.uk/dataset/samuel-dale)
- SEED in NSW (https://datasets.seed.nsw.gov.au/dataset/corridors-cessnock-lga)
We also adopt this PR in our Binder service (as the `CKAN dataset` repository): https://binder.depositar.io/, e.g.:
- https://binder.depositar.io/v2/ckan/https://data.depositar.io/dataset/binder-example-sea-turtle-sightings-in-taiwan
> [MRG] Add CKAN content provider

- repo2docker/docker.py
`ContainerConfig` has been removed, https://docs.docker.com/engine/deprecated/#container-and-containerconfig-fields-in-image-inspect says to use `Config`.
AFAIK the presence or absence of this field depends on the Docker host daemon, not docker-py.
Closes https://github.com/jupyterhub/repo2docker/issues/1354
> Docker engine: replace ContainerConfig with Config

- docs/source/changelog.md
> Add changelog for 2024.07.0

- tests/conftest.py
hasn't been `pipes.quote` since 3.3, pipes module is set to be removed in 3.13
> update import of shlex.quote

- repo2docker/buildpacks/conda/install-base-env.bash
- tests/conda/downgrade/verify
make sure we're always using conda-forge by default
it's unlikely any packages came from defaults for users in some years (due to channel priority, this would only happen for packages not on conda-forge, and would often result in a broken env anyway), but this ensures defaults channel is opt-in, as it should be for the Anaconda ToS.
> exclude defaults channel by default

- repo2docker/buildpacks/base.py
`exclude_paths` lists files and directories individually:
https://github.com/docker/docker-py/blob/7.1.0/docker/utils/build.py#L41-L48
[`TarFile.add`](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.add) defaults to `recursive=True`, leading to duplicate files being added. This may cause
https://github.com/manics/repo2podman/blob/141bf4f5902f58ac25ad9302eae23437e1d41e54/repo2podman/podman.py#L459-L460
to fail with `PermissionError: [Errno 13] Permission denied: ` when it tries to overwrite the file that was just extracted with a duplicate copy (possible race condition?)
> TarFile.add: don't add recursively

- repo2docker/__main__.py
avoids traitlets bug when this is called by `Application.__del__` (https://github.com/ipython/traitlets/pull/912)
closes #1379
> call close_handlers before garbage collection

- repo2docker/buildpacks/julia/julia_project.py
Repo2docker currently prints this warning when using a Julia project:
```
Warning: The Pkg REPL mode is intended for interactive use only, and should not be used from scripts. It is recommended to use the functional API instead.
└ @ Pkg.REPLMode /srv/julia/share/julia/stdlib/v1.10/Pkg/src/REPLMode/REPLMode.jl:382
[0m  at 12:24:22
```
This PR fixes that. I also used `Pkg.instantiate()` instead of `Pkg.precompile()` because it makes a bit more sense in this context: we want to guarantee that packages are instantiated (which precompiles at the end), not just that they are precompiled: https://pkgdocs.julialang.org/v1/api/#Pkg.instantiate
I believe that `resolve` already instantiates (and precompiles), but this is not defined in spec so it is good to add the `instantiate` call.
> julia_project.py: fix Pkg REPL api warning

- repo2docker/buildpacks/conda/activate-conda.sh
- repo2docker/buildpacks/conda/install-base-env.bash
- tests/conda/py35-binder-dir/verify
> Upgraded to micromamba 2.0.5

- repo2docker/contentproviders/doi.py
- tests/unit/contentproviders/test_figshare.py
- tests/unit/contentproviders/test_swhid.py
This was never used anywhere, and actually didn't even import - 'request' is actually urllib.request, not requests. It was never imported but used here!
> Remove unused _urlopen method

- repo2docker/app.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/utils.py
warnings.warn sidesteps all the json logging bits we do, and repo2docker will produce non-json output that binderhub then struggles to consume.
> Use self.log.warning instead of warnings.warn

- .github/workflows/test.yml
They idea behind the running tests on a weekly schedule is to have a rough timeframe for when external changes break our tests. We don't need to run them on forks.
> Don't run scheduled workflows on forks

- repo2docker/buildpacks/conda/activate-conda.sh
- tests/venv/start/postBuild/README.rst
- tests/venv/start/postBuild/verify
Closes https://github.com/jupyterhub/repo2docker/issues/1405
> `set -e` should not be set after conda environment is sourced

- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/conda/__init__.py
- repo2docker/buildpacks/julia/julia_project.py
- repo2docker/buildpacks/nix/__init__.py
- repo2docker/buildpacks/pipfile/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/r.py
- repo2docker/semver.py
- setup.py
We're making a breaking release:
https://github.com/jupyterhub/repo2docker/pull/1402
so we can use the opportunity to add other breaking changes. This only affects the Python version required to run repo2docker, it doesn't change the Python versions supported in environments.
> Require Python 3.9 to run repo2docker

- repo2docker/__main__.py
- repo2docker/app.py
- repo2docker/docker.py
- tests/unit/test_app.py
- tests/unit/test_args.py
pydocker uses the HTTP API (equivalent to `docker build`) which has been dead for ages. `docker buildx` (the interface to BuildKit) is what we *should* be using, but alas pydocker does not currently support it and I suspect it never will (https://github.com/docker/docker-py/issues/2230).
This PR simply shells out, as I think that's the way.
I'm going to list some intentional choices I've made here.
1. Intentionally replace the build functionality of the existing `DockerEngine` than make a new one. The old way is [deprecated](https://github.com/docker/buildx/issues/2297) and we should not support it.
2. Continue using `dockerpy` for all other non-build operations. It works fine and I don't see a need to change it right now.
3. Simply extract the tarball we construct elsewhere. This is …
> Shell out to `docker buildx build` to build images

- repo2docker/docker.py
We still use the docker python api to push images, and to run. So we need to set string_output to false, and simulate the json output on buildx. Alternatively we could completely get rid of the python API, but that's a much bigger lift (especially around registry credentials) that I don't want us to do right now.
Without this, push progress is reported as raw bytes in the binderhub UI
> Simulate json output from docker buildx build

- repo2docker/buildpacks/conda/activate-conda.sh
In regards of [the depreciation and future removal of `etc/profile.d/mamba.sh` from `libmamba`'s distribution](https://github.com/mamba-org/mamba/pull/3788/files#diff-21512f6a332b63c284b7d1ac549d08d5b827c56c5882aaa677ede79e8fcd65c4R1-R3).
> maint: Adapt mamba activation

- repo2docker/buildpacks/conda/activate-conda.sh
Resolves #1424 
Remove `-x` to be less spammy. Retain `-e` to exit on errors! (reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)
> [MRG] Disable bash trace output in conda activation script

- docs/source/contribute/tasks.md
This simplifies our release documentation by recommending others just create a release on GitHub directly. This means there is one less step to creating a new release.
> Simplify our release docs

- docs/source/use/actions-and-scripts.md
- docs/source/use/index.md
This does two things:
- Adds a page about postbuild and start workflows, so it's a bit more discoverable.
- Adds a note about root privileges and suggestions for what to do.
cc @chuckwondo
> Add note on root users and make postbuild actions more discoverable

- CONTRIBUTING.md
all of the links in the markdown doc that were pointing to the contribution sections hosted on readthedocs.io were broken.  now they won't be!  XD
> fix broken links in `CONTRIBUTING.md`

- docs/source/changelog.md
- repo2docker/buildpacks/base.py
- repo2docker/buildpacks/pipfile/__init__.py
- repo2docker/buildpacks/python/__init__.py
- repo2docker/buildpacks/r.py
- tests/unit/test_buildpack.py
There's a discussion somewhere (I can't remember where) about using https://github.com/astrofrog/pypi-timemachine or similar so Python packages can be installed as if `pip` were run in the past, similar to R. If we do this we should define the cutoff date for Python in the same way as for R, which is to use `runtime.txt`.
Something to consider is we haven't formally defined what `runtime.txt` contains.
Our docs state it should be one of:
- `name-version-yyyy-mm-dd`: (`r-<RVERSION>-<YYYY>-<MM>-<DD>`)
- `name-version`: (`python-x.y`)
https://github.com/jupyterhub/repo2docker/blob/e795060aec3555a6203ed79c3676765fb3f3b850/docs/source/config_files.rst?plain=1#L201-L207
Our tests say it can also be:
- name-yyyy-mm-dd
https://github.com/jupyterhub/repo2docker/blob/e795060aec3555a6203ed79c3676765f …
> Move `runtime.txt` parsing into base class

- docs/source/changelog.md
This copies the content of https://github.com/jupyterhub/repo2docker/releases/tag/2025.08.0 to the changelog in the documentation.
Closes https://github.com/jupyterhub/repo2docker/issues/1449
> Add missing 2025.08.0 release in changelog
