builder/app.py
builder/detectors.py

and S2I buildpack base for common python/conda
@yuvipanda's going to show me how to actually use this so I can verify that it works

add conda detector

---

repo2docker/detectors.py

setting build_image is enough, without overriding .build()

further simplify s2i buildpacks

---

.gitignore
Dockerfile
repo2docker/app.py
repo2docker/detectors.py
repo2docker/utils.py
setup.cfg
setup.py

- downloads s2i binary on linux & darwin
- puts it in repo2docker/s2i
- prepends repo2docker dir to PATH when launching s2i (append so existing s2i on PATH gets higher priority?)

bundle s2i in wheels

---

repo2docker/app.py

Makes it work on Linux and the default OS X install I think

Use same port in host and docker container

---

builder.md

Closes #9 
I'm not completely happy with the text here, but I think it's good enough to iterate on.

Add builder creation doc

---

repo2docker/app.py
repo2docker/detectors.py

Gives you a blank python3 environment
Fixes https://github.com/jupyterhub/binderhub/issues/40

Add a default build pack

---

s2i-builders/julia/Dockerfile

bumping julia version
@willingc

julia version bump

---

.travis.yml
tests/conftest.py
tests/external/datasci.repos.yaml
tests/external/reproductions.repos.yaml

So we know if we break something!
These all need better verification scripts tho.

Test some external repositories we care about

---

.travis.yml
repo2docker/detectors.py
setup.py

Mark repo2docker as requiring at least Python 3.4

---

.travis.yml

Makes it easier to verify what is going on.

Print stdout for all the tests!

---

repo2docker/app.py

And remove some traitlets we are no longer using

Add back --no-clean support

---

docs/source/conf.py
docs/source/index.rst
docs/source/samples.rst
tests/dockerfile/jupyter-stack/README.rst
tests/dockerfile/legacy/README.rst
tests/dockerfile/simple/README.rst
tests/julia/pyplot/README.rst
tests/venv/apt-packages/README.rst
tests/venv/numpy/README.rst
tests/venv/postBuild/README.rst
tests/venv/py2/README.rst

updating autogen examples

---

.gitignore
docs/source/conf.py
docs/source/samples.rst

let's see if this works (I'm gonna merge now)

fixing RTD build

---

docs/source/conf.py

let's see if this works (I'm gonna merge now)

fixing conf import

---

docs/doc-requirements.txt
readthedocs.yml

config file for RTD

---

MANIFEST.in
setup.py

This was causing all conda based builds to fail

Include package_data in setup.py

---

LICENSE

Add license - Issue #64

---

setup.py

Forgot to merge this after making a release

Bump verison number

---

README.md

Added this because I think some people will find it useful. It's also sort of a "case-study" in the components that need to be in a dockerfile in order for jupyterhub etc to work with it...

document `--debug`

---

readthedocs.yml

was causing readthedocs to fail!

docs type-o

---

repo2docker/app.py

register a custom excepthook that is called instead of the default traceback formatter. This produces a phase: failed message with the error.
This fixes the primary, controllable cause of #91
It's not entirely possible to rigorously ensure that *all* output is JSON from within the process itself, though.
Warnings etc. or debug messages that might come from other libraries will not be captured.
The only way to ensure truly rigorous log output is at one level higher than the repo2docker process itself.

avoid producing non-JSON output on errors

---

repo2docker/detectors.py
repo2docker/files/conda/environment.yml

Closes https://github.com/jupyter/repo2docker/issues/98

Upgrade to jupyterlab 0.28.0

---

docs/doc-requirements.txt
docs/source/conf.py

For better display on RTD, let's change the theme to the default, generic alabaster theme instead of the jupyter theme. cc/ @Carreau @choldgraf

Replace theme with alabaster

---

docs/source/faq.md
docs/source/index.rst

We get lots of questions that can be answered here!

Add a basic FAQ doc + 1 entry

---

repo2docker/detectors.py

[MRG] Remove intermediate containers for successful and failed builds

---

tests/venv/binder-dir/apt.txt
tests/venv/binder-dir/binder/apt.txt
tests/venv/binder-dir/postBuild
tests/venv/binder-dir/verify

Add tests for binder/apt.txt and binder/postBuild

---

repo2docker/buildpacks/base.py
tests/venv/apt-packages/apt.txt

fixing empty lines and comments in apt.txt

---

tests/memlimit.py
tests/memlimit/dockerfile/postBuild
tests/memlimit/non-dockerfile/postBuild

Temp fix for https://github.com/jupyter/repo2docker/issues/160.
Also includes a test to prevent drift

Remove symlink & just copy postBuild file instead

---

repo2docker/app.py
tests/argumentvalidation.py

Refactored argument validation test.
Closes #178

Fixed run argument check for mounting volumes. 

---

repo2docker/app.py
tests/argumentvalidation.py
tests/env.py

Submitted in partial fulfillment for #32 
I'm wet-behind-the-ears when it comes to Python; I'd appreciate constructive criticism :-)

Provide a flag to pass environment variables at runtime

---

repo2docker/app.py
tests/argumentvalidation.py

Added checks to gracefully handle docker connect errors

---

repo2docker/buildpacks/conda/freeze.py

I got tripped up by this and thought **I** had to somehow run it in an image rather than knowing the _script would do it for me_.

Switch freeze guidance to not be a directive

---

.travis.yml
CONTRIBUTING.md
dev-requirements.txt

Contains local dev, adding new libraries + freezing and release instructions.
Thanks to @willingc for editing the release process notes
Fixes #215 and #188

Add a CONTRIBUTING.md

---

repo2docker/app.py

ensures submodules, if any, are included
closes https://github.com/jupyterhub/binderhub/issues/447

clone recursively

---

docs/source/architecture.md

Add architecture document

---

CONTRIBUTING.md
repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/conda/environment.yml
repo2docker/buildpacks/python/requirements.frozen.txt
repo2docker/buildpacks/python/requirements.txt
repo2docker/buildpacks/python/requirements2.frozen.txt

This bumps `ipywidgets` to 7.1.1 (so a major version bump)
Also attempts at improving the version bump docs a bit while I'm at it :-)
closes #238

bumping ipywidgets version

---

docs/source/design.md

What do you think? What did I misrepresent or express too vaguely?

[WIP] Specify plans for stability in repo2docker dependency

---

repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/conda/environment.yml
repo2docker/buildpacks/python/requirements.frozen.txt
repo2docker/buildpacks/python/requirements.txt
repo2docker/buildpacks/python/requirements2.frozen.txt

* Upgraded `nteract_on_jupyter`
* Pinned tornado to `4.5.3`

upgrade nteract_on_jupyter to 1.5.0

---

repo2docker/buildpacks/r.py

Reverts jupyter/repo2docker#239
per https://github.com/jupyter/repo2docker/pull/239#issuecomment-372796941

Revert "Add shiny-server."

---

repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.yml
repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/python/requirements.frozen.txt
repo2docker/buildpacks/python/requirements2.frozen.txt
repo2docker/buildpacks/python/requirements2.txt

- bump ipykernel to 4.8.2
- pin tornado to 4.5.3
closes #257

refreeze environments

---

docs/source/config_files.txt
docs/source/install.rst
docs/source/usage.rst

Closes https://github.com/jupyterhub/binder/issues/79 #141 #125 
- Updates the installation instructions esp. headings and adds note re: Windows
- Reorders the configuration files into a rough order of priority/usage
- Create a few subheaders for more clarity in build steps in usage

Update installation and usage docs

---

repo2docker/buildpacks/python/__init__.py

Add docstrings to python3 and python2 buildpacks

---

CONTRIBUTING.md

Update freezing since the scripts now will use docker containers so there is no need for local versions of each Python release.

Edit CONTRIBUTING for freezing dependencies

---

repo2docker/buildpacks/docker.py

add docstrings to docker buildpack

---

repo2docker/buildpacks/conda/__init__.py

add docstrings for conda buildpack

---

repo2docker/buildpacks/base.py
repo2docker/buildpacks/python/__init__.py

closes https://github.com/jupyterhub/binder/issues/84 and closes https://github.com/jupyterhub/binder/issues/82
cc @betatim

fixing python2 search

---

README.md

Closes #281 
- Update example repo
- Add note about os support and link to windows in docs
- reflow text

Add note about os support and update example repo

---

repo2docker/buildpacks/legacy/__init__.py

add docstrings for legacy buildpack

---

repo2docker/buildpacks/python/__init__.py

Implements #249 
We should find repos to test this with to be sure that it works on real packages.
Some possibles examples to test: ipython, notebook, pandas, others?

Support setup.py in Python buildpacks

---

docs/source/usage.rst

Fix two typos

---

repo2docker/buildpacks/base.py

Release will be later today, but images are already being published with the betas.
closes #198

bump base image to ubuntu 18.04

---

.travis.yml
docs/source/index.rst

It should be easier to find us to ask questions, report bugs and to get
started contributing.
Right now you really need to know where to find us to find us.

Add links to the front page and modify travis

---

repo2docker/buildpacks/base.py

Here the thread https://github.com/jupyterhub/binderhub/issues/557

To add the user bin folder to the path

---

repo2docker/buildpacks/conda/install-miniconda.bash
tests/conda/simple-py2/verify

Following https://github.com/jupyterhub/jupyterhub/pull/1952 and issue linked there.

Switch to miniconda v4.5.1

---

repo2docker/app.py
tests/conftest.py
tests/dockerfile/binder-dir/binder/Dockerfile
tests/dockerfile/binder-dir/verify
tests/dockerfile/simple/Dockerfile
tests/dockerfile/simple/verify

Updated  app.py and conftest.py to test in all the builders that images can start notebooks servers.
Closes  #305

Test that images can start notebook servers in all the builders 

---

docs/source/usage.rst

Fix up some syntax errors in the usage document.

Fix some rst weirdness in the uage docs

---

repo2docker/app.py
tests/test_connect_url.py

so that the displayed connection URL is always correct
Closes #325

Specify custom_connect_url argument

---

repo2docker/buildpacks/base.py

Install nodejs/npm from nodesource

---

.travis.yml
docs/Makefile
docs/source/deploy.rst
docs/source/install.rst
docs/source/usage.rst

Adds building our docs in "warnings as errors" mode to the CI setup.

Fix warnings in the documentation build and add to CI

---

repo2docker/buildpacks/conda/__init__.py

closes #379 
There are a few ways to do this. I think this is the best but I'm open to suggestions.

compare yaml dict to mapping, not dict

---

CONTRIBUTING.md

Fixes #383 
Fixes #382 
This PR updates our contributing guide.

[MRG] Update contributing documentation

---

setup.py

This updates some of the metadata fields in our `setup()`.
This is the last thing I'd change before releasing 0.6.0 proper. After this is out we can start doing regular releases with all the bells and whistles (changelogs, planned features, etc).
@yuvipanda you ok with the email change?
@willingc any other PyPI things we should quickly tidy up?

Add more details to our setup() command

---

docs/source/_static/custom.css
docs/source/conf.py
docs/source/config_files.rst
docs/source/examples.rst
docs/source/howto/jupyterhub_images.rst
docs/source/howto/languages.rst
docs/source/howto/user_interface.rst
docs/source/index.rst
docs/source/install.rst
docs/source/usage.rst

This PR refactors a bit of the index, usage, and install pages. I tried to make the information a bit more discoverable from the main page and more cleanly separated out.

updating index, usage, and install docs

---

CONTRIBUTING.md
README.md

Add a checklist/guide to the contributing docs that gives people an idea of the steps requires to make a code change and a definition of when a PR is done.
This PR also updates the README a bit to link out to parts of our docs that seem relevant.

[MRG] Update the contributing docs

---

repo2docker/buildpacks/julia/__init__.py
repo2docker/utils.py
tests/test_clone_depth.py

PEP8 styling

---

.coveragerc
.travis.yml

[MRG] Switch to right sub-directory for coverage reports

---

.circleci/config.yml
docs/doc-requirements.txt
docs/source/conf.py

This sets up circleci to build docs and also adds the new jupyterhub theme

adding circleci preview and jupyterhub docs theme

---

docs/source/conf.py

adding back sidebars

---

repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.7.yml
repo2docker/buildpacks/conda/environment.yml

Uses pip instead of conda, since (AFAIK) conda installs
CHP and friends too.
Fixes #458

Add jupyterhub to base environment

---

repo2docker/app.py

I think this is better than the old one which was garbled as well as unclear.

[MRG] Tweak docstring to make it more understandable

---

docs/source/config_files.rst

removing note that env.yml is needed for julia

---

repo2docker/buildpacks/r.py

For https://github.com/jupyterhub/mybinder.org-deploy/issues/865

Bump nbrsessionproxy version

---

repo2docker/app.py
repo2docker/utils.py
tests/test_utils.py

The following functions have unit tests added:
- `execute_cmd`
- `chdir`
- `ByteSpecification.validate`
`maybe_cleanup` has been replaced with a `try...finally` in
its only place of use, which IMO is clearer.

Add unit tests for repo2docker/utils.py

---

.codecov.yml

Third time lucky?
This swaps the targets around, we want a minimal coverage of a diff/PR of 20% and for the project as a whole we are happy as long as it doesn't decrease (auto).

Swap codecov targets around

---

CHANGES.rst

Catch up the changelog and add in empty section for the next release.

Update changelog in preparation for releasing v0.7.0

---

docs/source/config_files.rst
docs/source/contributing/contributing.md

Adds a link to the change log in the contributing guide.
Also fixes a few small syntax errors.
Preview: https://134-90722372-gh.circle-artifacts.com/0/html/index.html

Fix typos and syntax errors in the documentation

---

ROADMAP.md

adding a roadmap link to the root

---

docs/source/howto/deploy.rst
docs/source/howto/user_interface.rst

This PR has a few minor documentation fixes. Mostly related to rendering code blocks and small changes like "Github" -> "GitHub"

Minor howto doc fixes

---

docs/source/contributing/tasks.md

make sure it's an annotated tag when creating a release

Add tag command snippet

---

repo2docker/contentproviders/base.py

Updated log info for local content provider

---

hooks/post_push

use the first 8 chars of the commit, not the last

fix docker commit tag

---

repo2docker/__main__.py

Check if '--debug' is set properly

---

Pipfile.lock

updates some pinned dependencies

regen Pipfile.lock

---

docs/source/config_files.rst

We ended up with duplicate labels, this PR fixes that.

Fix up double label trouble in the config file docs

---

docs/source/changelog.rst

Fix release date of 0.8.0

---

docs/source/changelog.rst

Adds a new blank section to the change log for people to start filling as PRs get merged.

[MRG] Reopen change log

---

docs/source/faq.rst

added some debug for R shiny

---

README.md
docs/issue_template.md

This adds an issue template and a pointer in the README to direct people towards discourse for support questions.

[MRG] Add issue template

---

docs/source/changelog.rst

Adds some missing entries to our change log.

[MRG] Update change log

---

docs/source/faq.rst

This mentions @yuvipanda 's blog post in the FAQ.

mentioning s2i in faq

---

docs/source/changelog.rst
repo2docker/buildpacks/python/__init__.py

This closes #589 which was our reminder to unpin pip again.

[MRG] Unpin pip again

---

repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.5.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.yml
repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.7.yml
repo2docker/buildpacks/conda/environment.yml

Updates the packages we provide for users.

[MRG] Bump nteract-on-jupyter to 2.0.12 and notebook to 5.7.8

---

docs/source/changelog.rst

add note to changelog

---

docs/source/changelog.rst

[MRG] Update change log in preparation for releasing v0.9.0

---

docs/source/changelog.rst

Bumping the release date in the changelog

bumping release date

---

docs/source/contributing/tasks.md

Updates to the guide for creating a new release that fills in some missing details.
I'll follow these steps to create the new release when we're ready in order to see if they're correct or not :-)

[MRG] release info updates

---

repo2docker/buildpacks/conda/environment.frozen.yml
repo2docker/buildpacks/conda/environment.py-2.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.6.yml
repo2docker/buildpacks/conda/environment.py-3.7.frozen.yml
repo2docker/buildpacks/conda/environment.py-3.7.yml
repo2docker/buildpacks/conda/environment.yml

Upgrade JupyterHub to 1.0

---

repo2docker/buildpacks/conda/__init__.py
repo2docker/buildpacks/conda/install-miniconda.bash

See discussion at the end of  jupyter/repo2docker#709 which we revert here.

Revert "[MRG] Remove more files during the image build to slimdown the image"

---

tests/external/reproductions.repos.yaml

I think switching to a different repo is the way to go to fix the issue in #729.
Closes #729.

[MRG] Switch to binder-examples/requirements for our tests

---

repo2docker/buildpacks/pipfile/__init__.py

these are structured files, no need to use regular expressions to parse them

parse pipfiles to determine Python version

---

docs/source/changelog.rst

Prepare release of 0.10.0

---

docs/source/index.rst

Tiny typo in docs/source/index.rst

---

.dockerignore

will hopefully fix dirty flag on docker hub

add hooks to dockerignore

---

azure-pipelines.yml

Add more of our test scenarios to the Azure setup.

[MRG] Add more test scenarios to Azure pipeline

---

docs/source/changelog.rst

Add missing changelog entry

---

repo2docker/buildpacks/julia/julia_project.py

Always more versions :) This is a bug-fix release, so should be entirely harmless.

Add support for Julia 1.3.1

---

azure-pipelines.yml
tests/unit/test_app.py

See if @manics idea from https://github.com/jupyter/repo2docker/issues/744#issuecomment-530867092 is it. Don't merge for now as it contains a test that always fails.

[MRG] Make sure the exit status gets passed along in Azure pipelines

---

docs/source/changelog.rst

Updating the changelog for 0.11.0 based on closed PRs since the last release.
Prompted by #841

[MRG] Update changelog for 0.11.0

---

docs/source/howto/export_environment.rst

Document loose conda export with --from-history

---

repo2docker/buildpacks/julia/julia_project.py

New version came out a while ago.

Add support for Julia 1.4.0

---

docs/source/config_files.rst

See Issue https://github.com/jupyter/repo2docker/issues/898

Add missing “:” for R code

---

tests/conftest.py

This upgrades our custom test finding and execution infrastructure to work with pytest v6 which was recently released.
https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent is the note about the deprecated feature we were using.

Upgrade custom test infrastructure for pytest 6.0.0

---

repo2docker/buildpacks/julia/julia_project.py

Add Julia 1.5.2 support

---

docs/source/usage.rst

closes https://github.com/jupyter/repo2docker/issues/926
Hopefully it is now clearer. Please feel free to make suggestions!

update docs for config dirs

---

repo2docker/buildpacks/conda/install-miniforge.bash
tests/conda/channel-dep/environment.yml
tests/conda/channel-dep/verify

Upgrade to latest mamba, fixes #973 including test for that case

Mamba 0.6.1

---

repo2docker/buildpacks/julia/julia_project.py

Add Julia 1.5.3 support

---

repo2docker/buildpacks/nix/install-nix.bash

buildpacks/nix: 2.3 -> 2.3.9

---

.github/workflows/docker.yml

<del>No relevant [changes](https://github.com/docker/build-push-action/blob/v2/UPGRADE.md) for us, I think</del> had to set tags, context
closes #1005

bump docker action version

---

repo2docker/contentproviders/zenodo.py
tests/unit/contentproviders/test_zenodo.py

Closes #1042 (see discussion there).

always unpack a single zenodo zip

---

.github/workflows/release.yml
README.md

A few refinements following https://github.com/jupyterhub/repo2docker/pull/1071

Update README quay.io URL, Add docker latest tag

---

docs/source/changelog.rst

It's about time we had a release! This also adds changelogs for the previous two releases (`2021.01.0` and `2021.03.0`)

[MRG] Release 2021.08.0

---

repo2docker/app.py

Default UI to JupyterLab

---

repo2docker/buildpacks/conda/__init__.py
repo2docker/buildpacks/conda/activate-conda.sh
repo2docker/buildpacks/conda/install-base-env.bash
tests/conda/binder-dir/verify
tests/conda/simple-py2/verify

instead of tmp, since we want it to stick around.

put micromamba in /usr/local/bin and use mamba for installs

---

docs/source/changelog.rst

With @yuvipanda's R improvements I think it's time for a release!
Created with
`github-activity -s 2021.08.0 | sed -r -e 's%\[#([0-9]+)\]\(https://github.com/jupyterhub/repo2docker/pull/[0-9]+\)%:pr:`\1`%' -e 's%\(\[\@([A-Za-z0-9-]+)\]\(https://github.com/[A-Za-z0-9-]+\)\)%by :user:`\1`%' > output.txt`
followed by some editing of `output.txt`

Update Changelog for release 2022.02.0

---

tests/dockerfile/binder-dir/binder/Dockerfile
tests/dockerfile/simple/Dockerfile

3.5 is very old and that's not what we aim to test with these

update Python in some dockerfile tests

---

RELEASE.md
docs/source/changelog.rst

- Fixes a typo
- Adds RELEASE.md to make it easier to find the instructions for a release

Post release fixes

---

repo2docker/buildpacks/repo2docker-entrypoint

Fix Read-Only filesystem permission issue for log file

---

repo2docker/contentproviders/dataverse.json

Add MPDL Dataverse

---

repo2docker/buildpacks/conda/install-base-env.bash
tests/conda/py35-binder-dir/verify

Upgrade to mamba 1.0

---

tests/external/reproductions.repos.yaml

These tests are failing on the main branch

Fix tests/external/reproductions.repos.yaml

---

.github/workflows/docker.yml
.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
tests/unit/contentproviders/test_dataverse.py
tests/unit/contentproviders/test_hydroshare.py

pre-commit update to fix ci

---

docs/source/faq.rst

Fixes https://github.com/jupyterhub/repo2docker/issues/1278

Update version of R available

---

repo2docker/buildpacks/conda/install-base-env.bash
tests/conda/py35-binder-dir/verify

Just a regular version bump on conda and mamba.

Update conda and mamba

---

repo2docker/buildpacks/conda/install-base-env.bash
tests/conda/py35-binder-dir/verify

Mostly a per-requisite test for #1366.

Update for mamba 1.5.8

---

repo2docker/buildpacks/conda/install-base-env.bash
tests/conda/py35-binder-dir/verify

Update to mamba 1.5.9

---

Dockerfile

Bumps our docker image base version

Bump alpine docker to 3.21

---

docs/source/cli.md
docs/source/contribute/tasks.md
docs/source/design.md
docs/source/index.md
docs/source/start.md
docs/source/use/repository.md

Closes https://github.com/jupyterhub/repo2docker/issues/1437

Avoid jupyter-repo2docker in the commad line
